---
title: Text
sidebar: components
appPreview:
  file: components/outputs/text/app-preview.py
listing:
- id: example
  template: ../../_partials/_new_component-example.ejs
  template-params:
    dir: components/outputs/text/
  contents:
  - title: Preview
    file: app-detail-preview.py
    height: 200
  - title: Express
    file: app-express.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQGJkAxASQA0BZAURQCU4B3AE4BLKsigBncRGScAHukFwJUjOgA6EAGaDSMZBIAWwiLmTCY6UoIrIAgpiJKIAEziCiAV2GbNagPreyAC8yN44UADmcP5aADbeLgAUmshpYcJYJuieFP5UchQpYAAqcIXqhMiVnJTuyAUUlUSVABJwcXGkyADKxqaVAJQEqemVAJqknsjUVEouiM2jaeFTFDl5jcWNQ8h0ADz7moPL6WmabloG7gBu7knZuURrG0QSyhLC5IOLMukAAs43IIsI09odTpcGuUij9TmclBRPIIZI8KFgyoUkoNqn8zudoJgQvZMEkAt43rd3CcIFUwBRcOgECh6TCwABfAC6QA
  - title: Core
    file: app-core.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXZTmdKQYVkAQUxEG1ACZwGRAK6cAOhFUZ0AfSXIAvMiU4oAczia6AGyXSAFKuQODnLN3QKKmqgA8KdsABU4H2VCZBCAUUo5ZG8KEKIQgAk4CwtSZABlLh4QgEoCe0cQgE1SBWRqKilpRHjCh0MyijcPWL9YvOQAYgAeHtVc+scHVVk6NjkANzkbV3ciJpaiVjhWVk5yXNqIYYABKQhZBixY7r6hsZig3y2h4akKBQYduYosQJ8bXLCd4aLoTB6MSYGwabScZZTOSDCChMAUXDoBAoeHXMAAXwAukA
- id: relevant-functions
  template: ../../_partials/_new_relevant-functions.ejs
  template-params:
    dir: components/outputs/text/
  contents:
  - title: ui.output_text
    href: https://shiny.posit.co/py/api/ui.output_text.html
    signature: ui.output_text(id, inline=False, container=None)
  - title: '@render.text'
    href: https://shiny.posit.co/py/api/render.text.html
    signature: render.text(fn=None)
- id: variations
  template: ../../_partials/_new_variations.ejs
  template-params:
    dir: components/outputs/text/
  contents:
  - title: Inline text
    description: Set `inline=True` within `ui.output_text()` to have text appear inline
      with the text that preceeds it.
    apps:
    - title: Express
      file: app-variation-inline-text-express.py
      shinylive: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaAGyXSAFKqYODHDF1QKymigA8ydsABU4H2V8JhCAUXI5Jm8yEIkQgAk4CwtiJgBlTm4QgEo8e0cQgE1iBSZKCilpRDDQwzKyNw9Yv1j43ggLLjg9Jn86BThc1RGIRwmwiFkaVjkANzkbV3cJRuaJFjgWFg5SXMRChwABKWm5DHbxxxmYoN8Do8mpMgU6cZWyDECfGzH1dB9MSoGwabQcTYLOS5MAAXwAukA
    - title: Core
      file: app-variation-inline-text-core.py
      shinylive: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaAGyXSAFKqYODHDF1QKymigA8ydsABU4H2V8JhCAUXI5Jm8yEIkQgAk4CwtiJgBlTm4QgEo8e0cQgE1iBSZKCilpRDDQwzKyNw9Yv1j43ggLLjg9Jn86BThc1RGIRwmwiFkaVjkANzkbV3cJRuaJFjgWFg5SXMRChwABKWm5DHbxxxmYoN8Do8mpMgU6cZWyDECfGzH1dB9MSoGwabQcTYLOS5MAAXwAukA
---

:::{#example}
:::

:::{#relevant-functions}
:::

## Details

Text displays a character string as normal text.

To make reactive text, follow three steps:

  1. Call `ui.output_text()` in the UI of your app to create a div in which to display the text. Where you call this function within the UI functions will determine where the text will appear within the layout of the app. Set the id argument of `ui.output_text()` to a unique value.

  2. Within the server function, define a new function whose name matches the id used above. The function should return the text to display. Shiny will rerun this function whenever it needs to build or update the output that has the matching id.

  3. Decorate the function with `@render.text`

See [Verbatim Text](verbatim-text.qmd) to display string values as they would appear in a computer console, in monospaced font on a shaded background.

:::{#variations}
:::
