---
title: "Cards and panels"
description: >
  Use cards and panels to define areas of related content in your Shiny app.

listing:
- id: relevant-functions
  template: ../../components/_partials/components-detail-relevant-functions.ejs
  contents:
  - title: ui.card
    href: https://shiny.posit.co/py/api/ui.card.html
    signature: ui.card(*args, full_screen=False, height=None, max_height=None, min_height=None, fill=True, class_=None, **kwargs)

  - title: ui.card_header
    href: https://shiny.posit.co/py/api/ui.card_header.html
    signature: ui.card_header(*args, container=tags.div, **kwargs)

  - title: ui.card_body
    href: https://shiny.posit.co/py/api/ui.card_body.html
    signature: ui.card_body(*args, fillable=True, min_height=None, max_height=None, max_height_full_screen=None, height=None, padding=None, gap=None, fill=True, class_=None, **kwargs)

  - title: ui.card_footer
    href: https://shiny.posit.co/py/api/ui.card_footer.html
    signature: ui.card_footer(*args, **kwargs)

  - title: ui.panel_absolute
    href: https://shiny.posit.co/py/api/ui.panel_absolute.html
    signature: ui.panel_absolute(*args, top=None, left=None, right=None, bottom=None, width=None, height=None, draggable=False, fixed=False, cursor='auto', **kwargs)

  - title: ui.panel_fixed
    href: https://shiny.posit.co/py/api/ui.panel_fixed.html
    signature: ui.panel_fixed(*args, **kwargs)

  - title: ui.panel_well
    href: https://shiny.posit.co/py/api/ui.panel_well.html
    signature: ui.panel_well(*args, **kwargs)

- id: variation-hello-card
  template: ../../components/_partials/components-detail-example.ejs
  template-params:
    dir: layouts/panels-cards/
  contents:
  - title: Preview
    file: app-hello-card-preview.py
    height: 200
  - title: Express
    file: app-hello-card-express.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXLOAD3QM4rVsk4x0pBhWQBXTgB0IygO6cK7eZyzEoDACYAKAJSJlyS9t36DAfXZwoBuAyOKwAQWSPnrj0TEADZQonYAvB4ARgDmALQG+gDWHiYWVgpYMMkGpKoQ7mAAysxwyFT8suqayFDIwEHcSQC6RuwUFOisiAD0PTEa7HJRusxpYGkQhKgUuOgIKGAVFGAAvs1AA
  - title: Core
    file: app-hello-card-core.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXZTmdKQYVkAQUxEArpwA6EORnQB9acgC8yaTigBzOEroAbaQBMAFHORXNnLMSgNzl6y633HS9nCgm4DCxAuQdYyYKLIXj5+oQTOwS7EhlCsrEpqoQBGOgC0Jg4A1qFxQQCUsYHxbg4mShmkJrgB8UFaMAUmpADuEBZgAMrMcMhUAB4inZwU7MhQyMCG3PkAumbsFBTorIgA9Ns6k+ySGXbMJaFnFcEXLhcXcnK+dGx+AG5+ZtzokhREpN9fP2eKU45BKiGK6GSrHu8mgmHUYkwZkUKk4RFYrz8F0IqAouHQCBQYFGFDAAF8lkA

- id: variation-implicit-card-body
  template: ../../components/_partials/components-detail-example.ejs
  template-params:
    dir: layouts/panels-cards/
  contents:
  - title: Preview
    file: app-implicit-card-body-preview.py
    height: 200
  - title: Express
    file: app-implicit-card-body-express.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXLOAD3QM4rVsk4x0pBhWQBXTgB0IygO6cK7eZyzEoDACYAKAJSJlyS9t36DAfXZwoBuAyOKwAQWSPnrj0TEADZQonYAvB4ARgDmALQG+gDWHiYWVgpYMMkGpKoQ7mAAysxwyFT8suqayFDIwEHcSQC6RuwUFOisiAD0PTEa7HJRuswmWKnKhKgUuOgIKGAVFGAAvs1AA
  - title: Core
    file: app-implicit-card-body-core.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXZTmdKQYVkAQUxEArpwA6EORnQB9acgC8yaTigBzOEroAbaQBMAFHORXNnLMSgNzl6y633HS9nCgm4DCxAuQdYyYKLIXj5+oQTOwS7EhlCsrEpqoQBGOgC0Jg4A1qFxQQCUsYHxWjAFJqQA7hAWYADKzHDIVAAeInWcFOzIUMjAhtz5ALpm7BQU6KyIAPQLOn3skhl2zCVYoSXFexAHcnK+dGx+AG5+ZtzokhREpPd3D+cpnOQliMXoyazH8mgmHUYkwZkUKk4RFYlz8B0IqAouHQCBQYC6FDAAF9xkA

- id: variation-restricting-growth
  template: ../../components/_partials/components-detail-example.ejs
  template-params:
    dir: layouts/panels-cards/
  contents:
  - title: Preview
    file: app-restricting-growth-preview.py
    height: 300
  - title: Express
    file: app-restricting-growth-express.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXLOAD3QM4rVsk4x0pBhWQBXTgB0IygO6cK7eZyzEoDACYAKGFH4B9dnE4BzdhQC8isACYArAAZ0-Z0TpyAGwDzVmJhagcAFQY5OABKRGVkZO1dfQNLOCgDOAYjZwBBZADyGyJQpiDuMuQcis50Ck5yZziklOcAGWk4FgbWORYDUhKGNg1kWDgKIjIIVjhiKgo5MeyGzlDq5DgAjSxkZ2QAKmRPZUJUClx0BBQwKn4KMABfAF0gA
  - title: Core
    file: app-restricting-growth-core.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXZTmdKQYVkAQUxEArpwA6EORnQB9acgC8yaTigBzOEroAbaQBMAFHORXNnLMSgNzl6y633HS9nCgm4DC2CiyIbkOkSsxEyGhtxhyL4RDJzoFJzkMmAAlATOLlYZADJCcCzJrJIsJqQhDGycIrBwFERkEKxwxFQUkrU+yZwRschwMRRYyBnIAFTIAKwADDkQedYwUAAennCcOuwUahkATAvo6xlLK1Z0ktFKiXDUagAqDJJwuciZcl-yv750bD8ADc-GZuOhJM1kKRIRCoe1WKw0hBMogPugoIi5NjoJh1GJMGZFCpOOFgX4foRUBRcOgECgwFR1hQwABfAC6QA

- id: variation-filling-outputs
  template: ../../components/_partials/components-detail-example.ejs
  template-params:
    dir: layouts/panels-cards/
  contents:
  - title: Preview
    file: app-filling-outputs-preview.py
    height: 300
  - title: Express
    file: app-filling-outputs-express.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXLOAD3QM4rVsk4x0pBhWTCIAEzgMiAV04AdCBKkzkMKBXQAbUhWOcARjlwmzyKGJMUtWgO6cK7ZOqzEoDAoAFOxwnADm7BQAvBpgAEwArAAM6PxxRHSqxsYA+qzEwtTRACoMqnAAlIhayHU+nH4BCrmhUEoMQXEAgsh0nDnc4ch2LmCVrhD1yAAC8h04pi5T9Up0I0tB1bXT9f3hRFD8yNEbFFisqpajrFs7uw78i2ZBwACMRPFEAMwAukTvIgAFiIAE5fhMVg9hBRVAwpvstIRUBRbAgUGAqPwKGAAL6-IA
  - title: Core
    file: app-filling-outputs-core.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXZTmdKQYVkAQUxEG1ACZwGRAK6cAOhH6DhyGFAroANqQp7OAIxy59h5FFbJ9FVaozoA+kuQBeZEpxQA5nAudHpK0gAUqshR3pxYxFAM4ZHRKexwnH7sFB7KYABMAKwADOgAHrkEySlRdAp6ei6sxFLUHgAqDApwlRDV0T7xiS5pULIMEWCiyHSc9dx+dgYOYACUPX1RAwnSLiak0rhhPqQKuqculhQTl7krK1XI9xBPjhCydGxyAG5yYdzopyIJzOFCIrDgrFYnHIK0QDwAAlI3nIcEsHu9FoYwrCHikZn4iFBSp5FhQsKwFCZLqxsbjokTUVjgABGIh5IgAZgAukQWUQACxEACcXKeG2QUgoCgYvXxrycmBJ4nQYWcbk4YO+ciehFQFAsCBQYCopQoYAAvlygA

- id: variation-content-divided-by-cards
  template: ../../components/_partials/components-detail-example.ejs
  template-params:
    dir: layouts/panels-cards/
  contents:
  - title: Preview
    file: app-two-cards-preview.py
    height: 320
  - title: Express
    file: app-two-cards-express.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXLOAD3QM4rVsk4x0pBhWQBXTgB0IygO6cK7eZywAbKLlJyKAfTK65MCCdUMMACnUATTQF4AjAHoATEXZxOAHN2CldFMABmAAYo9H5wgEpEZWRU5HVNbSxiKAYnezo5XV0TVmJhalcAFQY5OCSUtKaFbNynE38oJzgGe3CAYTbkd0TGptSW9D6wQbzh5AAjUidcUYhxtJbudGNS3U5u3vDWfcPwonCAZVOe8+QooncH5ABWBOUx9I0tFpy8gqKJTKFQg1Vq9WS6w2WT+7U6h2msycyG8a2hWSmAyG3kWy1WYHeUI2WwgO1MVH4FGmFIod3CAEEnMiaXSwGtCKgKLh0AgUGAaWAAL4AXSAA
  - title: Core
    file: app-two-cards-core.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXZTmdKQYVkAQUxEArpwA6EORnQB9acgC8yaTigBzOEroAbaQBMAFHORXNnLIai5SkikrLGYEJQHcGGCxGtAmyxiKAZzSyCorVDwpXY4KBM4BgswAGEwk2QARhkwAEoCSKjArXQ0zPDc5AAjUhNcfKKS0qstbnRnJVZDTmTU-N7+lPyifIBlPoGx5AAGIhyF5ABWFoC26zpJQ0Me4gY4ajUAFQZJOGKNqPW2mKz-Tet7uISklMqs5AAmZqun9q2Cr5KrZb51BpNQr-AEdCBdFxUAAeFDSyIos3yohM2XRmLAf1abW2u32h2OZwuMJu1KCXn6FHYahyAHpvrTAglODp2BQ1PkAMxzOboJFjVoFOSS+Qy5J0NgpABuH06ziITgoCKIrDgrFYnHIBUQrXQUD1cgt0Ew6jEmDMihUnG1SpS0sIqAouHQCBQYHRYAAvgBdIA
---

```{python}
#| include: false
import sys
sys.path.append("../..")

from docs.helpers import express_core_preview, shinylive_app_preview
```

Use cards and panels to define areas of related content.

:::{#relevant-functions}
:::

## Cards

Cards are a common organizing unit for modern user interfaces (UI). At their core, they're just rectangular containers with borders and padding. However, when utilized properly to group related information, they help users better digest, engage, and navigate through content.

### Hello `card()`

A `ui.card()` is designed to handle any number of "known" card items (e.g., `ui.card_header()`, `ui.card_body()`, etc) as unnamed arguments (i.e., children). As we'll see shortly, `ui.card()` also has some useful named arguments (e.g., `full_screen`, `height`, etc).

At their core, `ui.card()` and card items are just an HTML `div()` with a special Bootstrap class, so you can use Bootstrap's utility classes to customize things like [colors](https://getbootstrap.com/docs/5.2/utilities/background/), [text](https://getbootstrap.com/docs/5.2/utilities/text/), [borders](https://getbootstrap.com/docs/5.2/utilities/borders), etc.

:::{#variation-hello-card}
:::

### Implicit `card_body()`

If you find yourself using `ui.card_body()` without changing any of its defaults, consider dropping it altogether since any direct children of `ui.card()` that aren't "known" `ui.card()` items are wrapped together into an implicit `ui.card_body()` call.

:::{#variation-implicit-card-body}
:::

### Restricting growth

By default, a `ui.card()`'s size grows to accommodate the size of its contents. Thus, if a `ui.card_body()` contains a large amount of text, tables, etc., you may want to specify a `height` or `max_height`. That said, when laying out [multiple cards](#multiple-cards), it's likely best not to specify height on the `ui.card()`, and instead, let the layout determine the height.

Although scrolling is convenient for reducing the amount of space required to park lots of content, it can also be a nuisance to the user. To help reduce the need for scrolling, consider pairing scrolling with `full_screen=True` (which adds an icon to expand the card's size to the browser window). Notice how, when the card is expanded to full-screen, `max_height`/`height` won't affect the full-screen size of the card.

:::{#variation-restricting-growth}
:::

### Filling outputs

A `ui.card()`'s default behavior is optimized for facilitating filling layouts. More specifically, if a **fill item** (e.g., `ui.output_plot()`), appears as a *direct child* of a `ui.card_body()`, it resizes to fit the `ui.card()`'s specified height. This means, by specifying `height="250px"` we've effectively shrunk the plot's height from its default of 400 down to about 200 pixels. And, when expanded to `full_screen`, the plot grows to match the `ui.card()`'s new size.

:::{#variation-filling-outputs}
:::

### Multiple cards {#multiple-cards}

`ui.layout_column_wrap()` is especially nice for laying out multiple cards since each card in a particular row will have the same height (by default).

:::{#variation-content-divided-by-cards}
:::

Follow these steps to create an app with content separated into cards:

  1. Use `ui.layout_column_wrap()` to arrange multiple cards in a grid. Set `width` to control how many cards appear per row (e.g., `width=1/2` for two cards per row).

  2. Add `ui.card()` calls inside `ui.layout_column_wrap()`. You can use `ui.card_header()` and `ui.card_footer()` to create card headers and footers.

  3. Control the appearance and functionality of each card by passing additional arguments to `ui.card()`. For example, set `full_screen=True` to allow users to expand the card to fullscreen.

## Floating panel

:::{.column-screen-inset-right style="max-width:800px;"}
```{python}
#| output: asis
#| echo: false

shinylive_app_preview("app-panel-absolute-core.py", viewer_height=320, div_attrs=".p-0")
express_core_preview("app-panel-absolute-express.py", "app-panel-absolute-core.py")
```
:::

Follow these steps to create an app that has a panel floating over a main image.

First, to create the floating panel:

  1. Pass `ui.panel_absolute()` as the second argument of your Shiny UI page method, after `ui.img()`. Pass elements that you want to appear inside the panel to `ui.panel_absolute()`.

  2. Position the panel using the `top`, `bottom`, `left`, and/or `right` parameters. Set the size of the panel using the `height` and/or `width` parameters.

  3. If you want the panel to be draggable, set the `draggable` parameter to `True`.

In the example above, we used CSS to add [a scaling background image](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_backgrounds_and_borders/Resizing_background_images) to the page.
You can also use `ui.img()` to create this effect:

  1. Pass `ui.img()` to any Shiny UI page method (e.g., `ui.page_fluid()`). `ui.img()` creates an image.

  2. Pass the path or URL of your desired image to `ui.img()`'s `src` parameter. Set additional parameters to control the appearance of the image (e.g., `width` and `height`).


See also: [`ui.panel_fixed()`](https://shiny.posit.co/py/api/ui.panel_fixed.html). `ui.panel_fixed()` is equivalent to calling `ui.panel_absolute()` with `fixed=True` (i.e., the panel does not scroll with the rest of the page).

