---
title: Selectize (Multiple)
sidebar: components
appPreview:
  file: components/inputs/selectize-multiple/app-preview.py
listing:
- id: example
  template: ../../_partials/components-detail-example.ejs
  template-params:
    dir: components/inputs/selectize-multiple/
  contents:
  - title: Preview
    file: app-core.py
    height: 200
  - title: Express
    file: app-express.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQGJkAxASQA0BZAURQCU4B3AE4BLKsigBncRGScAHukFwJUjOgA6EAGaDSMZBIAWwiLmTCY6UoIrIAgpiJKIAEziCiAV2GbNagPreyAC8yN44UADmcP5aADbeLgAUmshpYcJYJuieFP4ScHFwxBTCAF5wSch0ADw1qemN6mAFRSXlcM1EtfUyjenNAMqFxbak6KXkUgBGhaT8iF3VdQ39yCDNAIx2zSjNAMKGpMLEcMjbS1sAQrvIB0cnZ5s3hHdgm-u398en559gAF9uis+msYJ44qV0EVggAVQSeM49VbIACUwN6jXCpFyOTyVDkFBSYAAblAEp0wOjNKjfK44FoDO4Se4ktlckQcRQ8UQCiphORUYtQcgAALONyCLAEigotyMskUpJClGNJQUTyCGRaZogdkULCtUYdZUA5p0tQheyYJIBby85nuWkQV5gCi4dAIFBuuCEwEAXSAA
  - title: Core
    file: app-core.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXZTmdKQYVkAQUxEG1ACZwGRAK6cAOhFUZ0AfSXIAvMiU4oAczia6AGyXSAFKuQODnLN3QKKm1nAtxiFTgBecDbIAMQAPOH2jjHKYF4+foFwcUQRURAxsWAAyt6+IqTo-uSsyABG3qQA7oipYZHRWcggcQCMonEocQDC7KScxHDIHfXtAEJdyL39g8Ntk4TTYG09UzMDQyNrYAC+aY2ZzcgwChb+6D66ACoMCsPpTcgAlAcZMYak7m4eVAAeFDsYAAblArCkwK9VM9VKpZHQ2HJgXIbK53EQvhQfkQvKxWJxyM86kcHAABKQQWQMLD-ChPeHIUHgmxEp4xKQUBQMTJ0OIgNEULAJArJFm7OKw6CYPRiTA2DTaTg4pFyGEQJZgCi4dAIFCauAAvYAXSAA
- id: relevant-functions
  template: ../../_partials/components-detail-relevant-functions.ejs
  template-params:
    dir: components/inputs/selectize-multiple/
  contents:
  - title: ui.input_selectize
    href: https://shiny.posit.co/py/api/ui.input_selectize.html
    signature: ui.input_selectize(id, label, choices, *, selected=None, multiple=False,
      width=None)
- id: variations
  template: ../../_partials/components-variations.ejs
  template-params:
    dir: components/inputs/selectize-multiple/
  contents:
  - title: Selectize with grouped choices
    description: To group the choices into categories, supply the `choices` argument
      with a dictionary of dictionaries. `ui.input_selectize()` will use the top-level
      keys as group labels.
    apps:
    - title: Preview
      file: app-variation-selectize-with-grouped-choices-core.py
    - title: Express
      file: app-variation-selectize-with-grouped-choices-express.py
      shinylive: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaAGyXSAFKqYODHDF1QKymlnAtxCZDgBecDZMAMQAPOH2jjHKYF4+foFwcRIRURAxsWAAyt6+wsSo-qQsTABG3sQA7oipYZHRWUwgDRnNzXEAjHGILd0ivUxxAMJsxByEcExdg-jDYF0AQkOj45PTy-XdI6tgYxNTM7tgAL5pjZkd2QBMQyBxN3N9a4fTT9tgNytICwcbTG+nxuJxe+3WRxBcVObSaWXOsKuzRgCgs-lQPl0ABU6Appuk4QBKC7tRyGYjuNweCgADzIdjAADcoFYUmBiapCapVLIaKw5Iy5DZXO4JBSyFSJF4WCwOKRCXUkUwAAJSCCyOgYWlkOG8pjM1k2BVwmJSMgKOiZGhxEAisgYBIFZJG05xbnQdB6UToGwabQcKUCuSEs4AXSAA
    - title: Core
      file: app-variation-selectize-with-grouped-choices-core.py
      shinylive: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaAGyXSAFKqYODHDF1QKymlnAtxCZDgBecDZMAMQAPOH2jjHKYF4+foFwcRIRURAxsWAAyt6+wsSo-qQsTABG3sQA7oipYZHRWUwgDRnNzXEAjHGILd0ivUxxAMJsxByEcExdg-jDYF0AQkOj45PTy-XdI6tgYxNTM7tgAL5pjZkd2QBMQyBxN3N9a4fTT9tgNytICwcbTG+nxuJxe+3WRxBcVObSaWXOsKuzRgCgs-lQPl0ABU6Appuk4QBKC7tRyGYjuNweCgADzIdjAADcoFYUmBiapCapVLIaKw5Iy5DZXO4JBSyFSJF4WCwOKRCXUkUwAAJSCCyOgYWlkOG8pjM1k2BVwmJSMgKOiZGhxEAisgYBIFZJG05xbnQdB6UToGwabQcKUCuSEs4AXSAA
---

:::{#example}
:::

:::{#relevant-functions}
:::

## Details

A selectize list creates a way to select one or more items from a list.

To use a selectize list that allows you to select <em>multiple</em> items:

  1. Add `ui.input_selectize()` to the UI of your app to create a selectize list. Where you call this function will determine where the selectize list appears within the app's layout.

  2. Specify the `id` and `label` parameters of `ui.input_selectize()` to define the identifier and label of the select list.

  3. Supply the `choices` parameter with either a list or dictionary of choices. If `choices` is a list, its elements become the select list values and labels. If `choices` is a dictionary, `ui.input_selectize()` uses the dictionary keys as the list values and the dictionary values as the list labels.

  You can also supply with `choices` a dictionary of dictionaries. `ui.input_selectize()` will use the top-level keys as group labels. See <em>Selectize with grouped choices</em> variation.

  4. The `multiple` parameter controls whether you can select multiple items at once. Set `multiple=True` to allow the user to select multiple values.

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of a selectize list:

  1. Use `input.<selectize_id>()` (e.g., `input.selectize()`) to access the selected value(s). The server value of a selectize list is a list of strings.

See also: [Selectize (Single)](../selectize-single/index.qmd) and [Select (Multiple)](../select-multiple/index.qmd). Select inputs and selectize inputs are similar, but have different interfaces and provide different ways of selecting multiple options. Selectize inputs also allow you to deselect items.

:::{#variations}
:::
