---
title: Action Link
sidebar: components
appPreview:
  file: components/inputs/action-link/app-preview.py
listing:
- id: example
  template: ../../_partials/components-detail-example.ejs
  template-params:
    dir: components/inputs/action-link/
  contents:
  - title: Preview
    file: app-detail-preview.py
    height: 200
  - title: Express
    file: app-express.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQGJkAxASQA0BZAURQCU4B3AE4BLKsigBncRGScAHukFwJUjOgA6EAGaDSMZBIAWwiLmTCY6UoIrIAgpiJKoxCsIBucJ9QAmcQUQArsKammoA+sHIALzIwThQAOZw4VoANsE+ABSayHlxwlgm6IEU4S5u5OFpJgDWOWiuwlU1ELXqhMgddk3kHQCURHQAPMO5+fGkpSVlVHIUDWSBlP4Dmv2hEH5aBv6eglnFpURTFDNEEsoSzRD9iON5AAJKW-5YcwsbMvnPcBUecCwcE8lEOEBmWH+LTqX3yyG2yCWKwOdwecOQSgogUEMi0HRARwokN6EGqdSy-QAvh1NmoYvZMFkIsELnt-F9OmAKLh0AgUFy4PMwJSALpAA
  - title: Core
    file: app-core.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXZTmdKQYVkAQUxEGcKMQqcAbnEnUAJnAZEArpwA6EPRnQB9bcgC8ybTigBzOEboAbbSoAUe5J8ucs3dJoojGTlyI0duAGt3NFlOUPCICJ1CZGTRWPJkgEoiAGIAHnyPLytSAP9AqgAPCmiyTUp1bL0svT01OjZ1RQZXPwCiMooKolY4VlY4iCzEYs8AASkINQYsatrWiC9kRelYxSw4RUo+iAqsYKmwyM3tjuR6xt6Zue3kKQpNBi26ZJB+igXDIQa6JVxZAC+yTa0Ew5jEmFchhMnFG3XUmxSYAouHQCBQ2LgNTAEIAukA
- id: relevant-functions
  template: ../../_partials/components-detail-relevant-functions.ejs
  template-params:
    dir: components/inputs/action-link/
  contents:
  - title: ui.input_action_link
    href: https://shiny.posit.co/py/api/ui.input_action_link.html
    signature: ui.input_action_link(id, label, *, icon=None, **kwargs)
  - title: reactive.event
    href: https://shiny.posit.co/py/api/reactive.event.html
    signature: reactive.event(*args, ignore_none=True, ignore_init=False)
---

:::{#example}
:::

:::{#relevant-functions}
:::

## Details

An action link appears as a link in your app and has a value that increments each time the user presses the link.

Follow these steps to add an action link to your app:

  1. Add `ui.input_action_link()` to the UI of your app to create an action link. Where you call this function will determine where the link appears within the app's layout.
  2. Specify the `id` and `label` parameters of `ui.input_action_link()` to define the action link's identifier and label.

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of an action link:

  1.  Use `input.<action_link_id()>` (e.g., `input.action_link()`) to access the value of the action link. The server value of an action link is an integer representing the number of clicks.

See also: [Action Button](../action-button/index.qmd)
