---
title: Slider Range
sidebar: components
appPreview:
  file: components/inputs/slider-range/app-preview.py
listing:
- id: example
  template: ../../_partials/components-detail-example.ejs
  template-params:
    dir: components/inputs/slider-range/
  contents:
  - title: Preview
    file: app-detail-preview.py
    height: 200
  - title: Express
    file: app-express.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQGJkAxASQA0BZAURQCU4B3AE4BLKsigBncRGScAHukFwJUjOgA6EAGaDSMZBIAWwiLmTCY6UoIrIArsKJKIAEziCiAQUybNagPoOyAC89sI4UADmcP5aADYOLgAUmshpYVgm6HYU-hJxwm6CKWD5he7qhMiVAMoFRZVEMCbBAAxNUHLBAIyt7cgAblAJcMHAAMwArEQAbJMAugCURHQAPKup6Q5YpDnZuVRyuQPuAEZQFBYlQyOVy5qLvq5wWgbuJ8VZOUS7FPtEEmUEmE5EWiE2aQAAs4ilhDhQIcg3K8bnY4EkwYj0sglBQ7IIZFpKiAvhQsGUihiAL6VJ5qELIbzoJIBBwA97uR4QKpgCi4dAIFC8uBHMBU+ZAA
  - title: Core
    file: app-core.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXZTmdKQYVkAV05EG1ACZwGRAIKYAOhFUZ0AfXHIAvGM44oAczia6AG3HSAFKuQODWbulEVNrC51kM7YT95yyoTIwQDKXj7BRDDcugAMMVAAHroAjPGJyABuUFZwusAAzACsRABsJQC6AJREAMQAPI32juJYpG6u7lTJ7tlyAEZQFPx+ufnBdao1qqqydGxyA74ubkSdFN1ErHCsrJzkNYitDgACUhA+WL0Up8gLOXmicDbH947IUhSiDBDIdGCIDWFCwAR8bwAvsE5tBMHpkEp0DYNNoJEsGCtZhAQmAKLh0AgUHi4H0wJCqkA
- id: relevant-functions
  template: ../../_partials/components-detail-relevant-functions.ejs
  template-params:
    dir: components/inputs/slider-range/
  contents:
  - title: ui.input_slider
    href: https://shiny.posit.co/py/api/ui.input_slider.html
    signature: ui.input_slider(id, label, min, max, value, *, step=None, ticks=False,
      animate=False, width=None, sep=',', pre=None, post=None, time_format=None, timezone=None,
      drag_range=True)
  - title: ui.output_data_frame
    href: https://shiny.posit.co/py/api/ui.output_data_frame.html
    signature: ui.output_data_frame(id)
  - title: render.data_frame
    href: https://shiny.posit.co/py/api/render.data_frame.html
    signature: render.data_frame(fn=None)
  - title: render.DataTable
    href: https://shiny.posit.co/py/api/render.DataTable.html
    signature: render.DataTable(self, data, *, width='fit-content', height='500px',
      summary=True, filters=False, row_selection_mode='none')
---

:::{#example}
:::

:::{#relevant-functions}
:::

## Details

A slider is a widget that lets you drag to select numbers, dates, or date-tifrom a specified range. You can use a slider to select either a single value or a range of values.

To add a slider that lets the user select a range of values:

  1. Add `ui.input_slider()` to the UI of your app to create a slider. Where you call this function will determine where the slider will appear within the app's layout.

  2. Specify the `id` and `label` parameters of `ui.input_slider()` to define the identifier and label of the slider.

  3. Use the `min` and `max` parameters to define the minimum and maximum values of the slider. `min` and `max` can be numbers, dates, or date-times. Dates and date-times can be provided from the `datetime` module with the `date()` or `datetime()` functions, respectively.

  4. Pass a list with two elements to the `value` parameter. These elements define the initial range. `value` can be a list of numbers, dates, or date-times.

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of a slider:

  1. Use `input.<slider_id>()` (e.g., `input.slider()`) to access the value of the slider. If `value` is a list and the slider specifies a range, the server value of a slider will be a list of length 2.

See also: [Slider](../slider/index.qmd)
