---
title: DataTable
sidebar: components
preview: '<div class="p-4 w-100 h-100">
<table class="w-100 h-100 my-0 ">
<thead>
<tr style="border-top:2px solid #1D1F21;border-bottom:2px solid #1D1F21;">
<th class="fw-600 p-90 px-2 py-1" tabindex="0" colspan="1" scope="col">
<div>This</div>
</th>
<th class="fw-600 p-90 px-2 py-1" tabindex="0" colspan="1" scope="col">
<div>That</div>
</th>
</tr>
</thead>
<tbody tabindex="0">
<tr tabindex="-1" data-index="0" data-key="0">
<td class="fw-500 p-90 px-2 py-1">And</td>
<td class="fw-500 p-90 px-2 py-1">The</td>
</tr>
<tr tabindex="-1" data-index="1" data-key="1">
<td class="fw-500 p-90 px-2 py-1">Other</td>
<td class="fw-500 p-90 px-2 py-1">Thing</td>
</tr>
</tbody>
</table>
</div>'
listing:
- id: example
  template: ../../_partials/components-detail-example.ejs
  template-params:
    dir: components/outputs/datatable/
  contents:
  - title: Preview
    file: app-core.py
  - title: Express
    file: app-express.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZdKAG3gfWoHMBXAJYQAzskEx0pBhWTtSUACYB9HhAHCRAHQiNmyEQAthucZOmyG1RXAY69LIyaxwAHuisixEqTORCdHTUNUWQAXjkFFWChUQAKAEpAiCEsQwAmOK0wAAUOLmQcvljtMCSIZIABKwgbBixFKAooZUZYOGRkAGJkAB5enRs6VmLNZUU6RMQdTs6rCn4GCGQauqwAESaoABUoACN2ODiYzQTOnv6dQlQKXB5aMCpXCjAAXwBdIA
  - title: Core
    file: app-core.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZdKAG3gfWoHMBXAJYQAzskEx0pBhWTtSUACYB9HhAHCRAHQiNmyEQAthucZOmyAgpiINqiuAyJCdOtRtHIAvHIUr3QqIAFACUrtCYykLeyEI4ULxwynTsQopBOshZsYJYhgBMGWAAChxcyMV8gdpgIQSZ2XGk-BToLcqKUBRQyQywcEUBmh10WrVEyADEyAA8MzphEOEOdAaOAG6OQcJtFETNrS1EInAiIoLkIYgNWQACdhAODFid3b39WdNzN8grrFXDRR0ULXCDZcHIOwUfgMMEPJ5YAAiXSgABUoAAjdgDIaiEKfWbzJbEjDoGLWdBBUlRQTHDaORaEVAUXA8WhgKgADwoYAAvgBdIA
- id: relevant-functions
  template: ../../_partials/components-detail-relevant-functions.ejs
  template-params:
    dir: components/outputs/datatable/
  contents:
  - title: ui.output_data_frame
    href: https://shiny.posit.co/py/api/ui.output_data_frame.html
    signature: ui.output_data_frame(id)
  - title: '@render.data_frame'
    href: https://shiny.posit.co/py/api/render.data_frame.html
    signature: render.data_frame(fn=None)
  - title: render.DataTable
    href: https://shiny.posit.co/py/api/render.DataTable.html
    signature: render.DataTable(self, data, *, width='fit-content', height='500px',
      summary=True, filters=False, row_selection_mode='none')
- id: variations
  template: ../../_partials/components-variations.ejs
  template-params:
    dir: components/outputs/datatable/
  contents:
  - title: Select Rows
    description: Set `row_selection_mode` in `render.DataTable()` to `"single"` to
      allow the user to select one row at a time. Set it to `"multiple"` to allow
      the user to select multiple rows at a time. Access the selection(s) as `input.<id>_selected_rows()`.
    apps:
    - title: Preview
      file: app-variation-select-rows-core.py
      height: 350
    - title: Express
      file: app-variation-select-rows-express.py
      shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZdKAG3gfWoHMBXAJYQAzskEx0pBhWTtSUACYB9HhAHCRAHQiNmyEQAthucZOmyG1RXAY69LIyaxwAHuisixEqTPER0fgoiIR0dNQ1RZABeOQUVCKFRAAoASjCIISxDACZkrTAABQ4uZEK+JO0wdIgMgAErCBsGLFCmuDpkJgB3ETTEHWQhrtJemP9AihwKzWVFOmUROHY4YioVHr7UoYBiZAAefcHhpZW1uEVxgqICrAArUmFkkQoGZMFtumlxfwMLC+Sm1S20EnU2yGWS2QBQAcuQ4AVjkMrBR+AwIMg6AUAEqjMSnVbrFAgAnnRQAX0RtWpDWstiwiigFCgykYsAR7U6iVm836SK6cFR6IF7RaABEmVAACpQABGK2S3NERB6i2WhME5GUMFINmiBREwl4KwK22Qe0OOkIqAouB4tDAVFcFDA5IAukA
      height: 350
    - title: Core
      file: app-variation-select-rows-core.py
      shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZdKAG3gfWoHMBXAJYQAzskEx0pBhWTtSUACYB9HhAHCRAHQiNmyEQAthucZOmyAgpiINqiuAyJCdOtRtHIAvHIUr3QqIAFACUrtCYykLeyEI4ULxwynTsQopBOshZsYJYhgBMGWAAChxcyMV8gdpgIQSZ2XGk-BToLVGCRUwA7jV1DVlNLW0UyopQFFDJDLBwRQGaY3RatfUQYRDhDnQGjgBujkHCI0TNrS1EInAiIoLkIYgDyAACdhAODFjjk9OzT9usKqLRR0UKPCDZSHIOwUfgMCFvD5YAAiEygABUoAAjdhzBaiWykbrKK644gUO4QZQwUgOLwrW7qXErEJZADEyAAPJzwpDXvZHFgXBDsgCeiIwU9IeKYscWjggaIliS4GSqCpxaF2VyeSKobs1XBFDEVkQVlgAFakYRBEQUBhHVl0aTicQQkQWI1BcUhVmCHYy1VXZArABy5DgKyl2RhcIhyzAACUiWJSXByUaUCA0xnFABfKObIsYdAxazoIIljqXfaODaEVAUXA8WhgKgADwoYDzAF0gA
      height: 350
  - title: Filterable Table
    description: Set `render.DataTable(filters=True)` to add a row of filter options
      to the header row. Users can interact with these options to filter the table.
    apps:
    - title: Preview
      file: app-variation-filterable-table-core.py
      height: 350
    - title: Express
      file: app-variation-filterable-table-express.py
      shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZdKAG3gfWoHMBXAJYQAzskEx0pBhWTtSUACYB9HhAHCRAHQiNmyEQAthucZOmyG1RXAY69LIyaxwAHuisixEqTORCdHTUNUWQAXjkFFWChUQAKAEpAiCEsQwAmOK0wAAUOLmQcvljtMCSIZIABKwgbBixFKAooZUZYOB0bOlZizWVFOkTEHWRR5CsKfgYIcetbLAARJqgAFSgAI3Y4OJjNIjpBdioGETCVhn44BNGAYmQAHnudQlQKXB5aMCpXCjAAXwAukA
      height: 350
    - title: Core
      file: app-variation-filterable-table-core.py
      shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZdKAG3gfWoHMBXAJYQAzskEx0pBhWTtSUACYB9HhAHCRAHQiNmyEQAthucZOmyAgpiINqiuAyJCdOtRtHIAvHIUr3QqIAFACUrtCYykLeyEI4ULxwynTsQopBOshZsYJYhgBMGWAAChxcyMV8gdpgIQSZ2XGk-BToLcqKUBRQyQywcEUBmh10WrX1EGEQ4Q50Bo4Abo5Bwm0URM2tLUQicCIiguQhiA1ZAAJ2EA4MWJ3dvf2nyLOsVcOKdKEnENm-yHYUfgMH6Xa5YAAiXSgABUoAAjdgDIaiIh0QTsKgMEReaEMfhwEJZADEyAAPKTwjoMOgYtZ0EFqVFBDtFo4poRUBRcDxaGAqAAPChgAC+AF0gA
      height: 350
  - title: Set Table Size
    description: Set the `height` and `width` parameters of `render.DataTable()` to
      constrain the output size of the table.
    apps:
    - title: Preview
      file: app-variation-set-table-size-core.py
      height: 350
    - title: Express
      file: app-variation-set-table-size-express.py
      shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZdKAG3gfWoHMBXAJYQAzskEx0pBhWTtSUACYB9HhAHCRAHQiNmyEQAthucZOmyG1RXAY69LIyaxwAHuisixEqTORCdHTUNUWQAXjkFFWChUQAKAEpAiCEsQwAmOK0wAAUOLmQcvljtMCSIZIABKwgbBixFKAooZUZYOB0bOlZizWVFOkTEHWRR5CsKfgYIcetbLAARJqgAFSgAI3Y4OJjNIgB3QUUKQzDsgGYABkv0V2yiQzhBXkMKM7B0gFYbu7LRgGJkAAeIE6QioCi4Hi0MBUVwUMAAXwAukA
      height: 350
    - title: Core
      file: app-variation-set-table-size-core.py
      shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZdKAG3gfWoHMBXAJYQAzskEx0pBhWTtSUACYB9HhAHCRAHQiNmyEQAthucZOmyAgpiINqiuAyJCdOtRtHIAvHIUr3QqIAFACUrtCYykLeyEI4ULxwynTsQopBOshZsYJYhgBMGWAAChxcyMV8gdpgIQSZ2XGk-BToLcqKUBRQyQywcEUBmh10WrX1EGEQ4Q50Bo4Abo5Bwm0URM2tLUQicCIiguQhiA1ZAAJ2EA4MWJ3dvf2nyLOsVcOKdKEnENm-yHYUfgMH6Xa5YAAiXSgABUoAAjdgDIaiIgAd0Eigohi8YwAzAAGfHoAAeYyIhjggl4hgoOLA+QArETSbUsgBiZAAHk54R0GHQMWs6CC-Kigh2i0cU0IqAouB4tDAVGJFDAAF8ALpAA
      height: 350
  - title: Customize Summary Statement
    description: 'Set `summary` in `render.DataGrid()` to `False` to remove the statement
      "Viewing rows 1 through 10 of 20". Set it to a string template containing `{start}`,
      `{end}`, and `{total}` tokens, to customize the message.

      '
    apps:
    - title: Preview
      file: app-variation-customize-summary-statement-core.py
      height: 350
    - title: Express
      file: app-variation-customize-summary-statement-express.py
      shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZdKAG3gfWoHMBXAJYQAzskEx0pBhWTtSUACYB9HhAHCRAHQiNmyEQAthucZOmyG1RXAY69LIyaxwAHuisixEqTORCdHTUNUWQAXjkFFWChUQAKAEpAiCEsQwAmOK0wAAUOLmQcvljtMCSIZIABKwgbBixFKAooZUZYOB0bOlZizWVFOkTEHWRR5CsKfgYIcetbLAARJqgAFSgAI3Y4LJmxvZjNAhG9sZF+GBgoBlww7IA1QWtSZDpBdigxEBFmmQBfZCgyBA1n+NiBFFIzXYv2yRGQAGJkAAeJHHUblQioCi4Hi0MBUVwUMC-AC6QA
      height: 350
    - title: Core
      file: app-variation-customize-summary-statement-core.py
      shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZdKAG3gfWoHMBXAJYQAzskEx0pBhWTtSUACYB9HhAHCRAHQiNmyEQAthucZOmyAgpiINqiuAyJCdOtRtHIAvHIUr3QqIAFACUrtCYykLeyEI4ULxwynTsQopBOshZsYJYhgBMGWAAChxcyMV8gdpgIQSZ2XGk-BToLcqKUBRQyQywcEUBmh10WrX1EGEQ4Q50Bo4Abo5Bwm0URM2tLUQicCIiguQhiA1ZAAJ2EA4MWJ3dvf2nyLOsVcOKdKEnENm-yHYUfgMH6Xa5YAAiXSgABUoAAjdgDJ5-bJDUQTFEokT8GAwKAMXBeMYANUE9lIyDognYUDEIBE3RkAF9kFBkCB7CyHOyKKRuuwmWMiMgAMTIAA84uR2Sm4Qw6Bi1nQQXlUUEO0WjimhFQFFwPFoYCoAA8KGAmQBdIA
      height: 350
---

:::{#example}
:::

:::{#relevant-functions}
:::

## Details

A DataTable presents tabular data in a figure-like view with a minimum of grid lines.

To make a reactive Data Table, follow three steps:

  1. Call `ui.output_data_frame()` in the UI of your app to create a div in which to display the table. Where you call this function within the UI functions will determine where the table will appear within the layout of the app. Set the id argument of `ui.output_data_frame()` to a unique value.

  2. Within the server function, define a new function whose name matches the id used above. The function should assemble the table to display and then return the table wrapped in `render.DataTable()`. Shiny will rerun this function whenever it needs to build or update the output that has the matching id.

  3. Decorate the function with two decorators:

      1. `@output`
      2. `@render.data_frame`

A DataTable can also collect input from the user. To allow this, set `render.DataTable(row_selection_mode="single")` or `render.DataTable(row_selection_mode="multiple")` to allow the user to select one or more rows of the DataTable.

The indices of the selected rows will be accessible within the server function as a reactive variable returned by `input.<id>_selected_rows()`, where <id> is the id of the `ui.output_data_frame()` associated with the table.

The value returned will be `None` if no rows are selected, or a tuple of integers representing the indices of the selected rows. To filter a pandas data frame down to the selected rows, use `df.iloc[list(input.<id>_selected_rows())]`.

If your table is a data frame that uses the pandas styler, replace `ui.output_data_frame()` with `ui.output_table()` and `@render.data_frame` with `@render.table`.

See also [Data Grids](../data-grid/index.qmd)

## Variations

:::{#variations}
:::
