---
title: File Input
sidebar: components
appPreview:
  file: components/inputs/file/app-preview.py
  static: true
listing:
- id: example
  template: ../../_partials/components-detail-example.ejs
  template-params:
    dir: components/inputs/file/
  contents:
  - title: Preview
    file: app-detail-preview.py
    height: 200
  - title: Express
    file: app-express.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXZTmdKQYVkDOFGIVOANzgAdCI2ZsuPLHAAe6Ma1Z8BQkd3QBXCkTEQAJnAZETnBQodZjZgPp1OAGzgAKOTA6QKJAgAVOYgBrZChkL18iKB54n3kwAEpkZABiZAAefKcwAEkIUxEEuGQrKAooRECnCAUAAUsbBiwqDQoFGzpkCl6-DMaIbOyxChMGCbcKLDpR7LzChUJUClx0BBQwHoowAF8AXSA
  - title: Core
    file: app-core.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXZTmdKQYVkAQUxEG1ACZwGRAK6cAOhFUZ0AfSXIAvMiU4oAczia6AGyXSAFKuQODnLN3QKK5zhbh2wdZYTIAQAKnMQA1shQyHRecERQPDFxAQCURMgAxMgAPDn2jgEAkhBuIrHeyNJQFFCIAQQFDoak7mWaVAAeFL4U3WmNEKmqIxCydGxyAG5yNq7uRK0UZUSscKysnOSp9RCOyAACUmNyWF0UTVVwE309O5f7UhQKDHvzFFh0NqkO2Xmj6kwejEmBsGm0nFW0zkwwggTAFFw6AQKARcG6YAAvgBdIA
- id: relevant-functions
  template: ../../_partials/components-detail-relevant-functions.ejs
  contents:
  - title: ui.input_file
    href: https://shiny.posit.co/py/api/core/ui.input_file.html
    signature: ui.input_file(id, label, *, multiple=False, accept=None, width=None,
      button_label='Browse...', placeholder='No file selected', capture=None)
  - title: express.ui.input_file
    href: https://shiny.posit.co/py/api/express/express.ui.input_file.html
    signature: express.ui.input_file(id, label, *, multiple=False, accept=None, width=None,
      button_label='Browse...', placeholder='No file selected', capture=None)
- id: variations
  template: ../../_partials/components-variations.ejs
  template-params:
    dir: components/inputs/file/
  contents:
  - title: Read a CSV file into pandas
    description: You can limit the data type to only CSV files that can be read into
      pandas.
    apps:
    - title: Preview
      file: app-variation-read_csv-core.py
    - title: Express
      file: app-variation-read_csv-express.py
      shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQEsZ1SAnC5dKCAEygGdk+7LgB0IAM2akYyXgAs6EXMgZNWyZnCjEKdAG5xREqTPmKscAB7oNvfipZsF6AK4UiG7nGZFndQ5Ok5BVwsClx0ODtGB2QAMToAGzgASXFSUVFfLCdXAH0xRLgACmEwHIp8wtKiUoBhWVJSXjhkWoBlADU4qsIBYmI4dAoAXmBSrGJeXVKAXSIYZwSddCTh2KgE5oBKTLpsiBcK4lk4YgBrACNSC1yAc0lndBKIZFfkUt4KKApeatE395gNrOGAwKDMJRtL4-P4vN7HUh0Aa8UalABKpAA7q1SM5KNVAbVSAkQS8iXiKAS6sTScgAHKwSKzAj-N7NJLaOBcVFgDHY8n43rUkkwMm4wU1MBEkUvBnwX5gOaiHYQDIQAACGi0On0Ew2xFEXDgYnY4OaXEqSSKW0QrNeBSSyGGygOrn2h0txRVALoJodLTo-Dp5DgtrhANeGgozmYL3QXCwABFvlBYsxGda7eo4NHY0IsFqLZNdEV-cAAAwzMZgHhfDgUWSzFVqzXUI3MLC1qD5dPwQ3GmQgsEQ61hgFcE3OjjMc2ezOq8PKE0T8yMMJjiORnMxuMJ5NfNMZ5uLgDEyAA4jnkA2WpJsWQKUQyDLkA-KEROFxXzTRchoPLkFIE0b2QfdU17AxFzvXI3zYZ0VzkDA4ArGYs2fUkYPFODkAQ2QkOAABGVDF3-SInRwsQJh-CBeFCYlAwoecAXQ0VclI-hnSpMAsAAK0RCAik+ZgilIrZkDEFg-0ZF0pPlY8ATPWotSoAQ-zgbEwMPeBr1IHDAxWKAlBAhQJOYMEdHILMTNIXIJ3I+MkxTLTihALMAXRLEcQpUoUGAaDYKVRd3KlaivMFXyWIgTCKUCzdXmFWk5SZWhgEitjGV4WK3gAX3kt4z3KLBPm+XhrWUfgoGQBIGMAk0hIUW5eAAbkHC5mjYEDIv4C4+C5QCXhA9lTioERT1fE5ziuCwmSg7c82s2zKISUhiGARAiEK4qfmtYjejAMIIlofbLAoMBspmIA
    - title: Core
      file: app-variation-read_csv-core.py
      shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQEsZ1SAnC5dKCAEygGdk+7LgB0IAM2akYyXgAs6EXMgZNWyAIKYizOFGIU6ANzjbqXOMyIBXOqNEZ0AfRvIAvMhs4oAcziOxADY2XAAUosgRHnRYCuhWFP50AXBhEJHpyMJgsfGJyVlEWQDCsqSkvHDIRQDKAGrIAGJJcAUCxMRw6BSuwFlYxLyGWQC6RDBWAQboya4NUAEV4ZEAlARLEZ45CcSycMQA1gBGpAAejt6SVuipGZFZvBRQFLwF6xlZ1VYwMFDMStWPZ6vNK3ZA7Uh0Dq8HpZABKpAA7lVSFZKK1iqQgjA0kUUWjCJkwLisWkAHKwOAvMCjN7pCrJfRwLgwsDwpG41EUdFEzFfHF4rkEjEk5Dk+BUmkgiKrN6eFEUOIJHiPfzMClhMC8L4-P5ZGUQZZ2CCicxiGQWYzMEJbIjyxVECq8Xh0cjLRBvAACOj0BmM-XmxDepvYvwqXDyKTdtMiYmabmUEEVMUTuVjyRChqlGToZrTlTo-FJ5Dg7qzoOQOgoVmYaXQXCwABEnlAGmr4BnoxFK9Xa-XveGBoYQnngAAGYa9MDKjBPWQjTOenTcCxYaeqilBuBmrXfX64DOl8tcM3uDjMMMRjvGsuRHPIY9YOCMCi4Q-lyLdmtCRvN1vqhc3hEADEyAAOJwGwFC7BWiJggKRBkCKZCckQnBcHBIrQOKyCkGaUGVE2jx-vAnYwQijjIZQ8YPnIGBwGOwykYhfIUQK1FiFgtHoPRACMjGAcgWGUux-S8tivBYBQmIFhQV7lsx2KOEJ-DuNyWAAFYQhAIQPFaQnLMgYgsIJFIJiZ4oAeWIFFN6VACIJcBIoRLZtpUUn3gW0xQEo+EJkZzA-AY5CkQoRmOMe8Z1j+RGuSEICkekcKwRy+IoMAkjkZRFCSu+dw8iKKWCmlCkQKxnI5blhLEnyooUlSxViaVykVbcAC+lmgiBWycYCvAZso-BQMgAQyTh24UMwCjeLwADcMhWIcFSQdBJX8IcfBMjhaS+fSexUCIAkgTsexHKclKkZ+aShaQ4UcQEpDEMAiBEN1DxPH1yz8UaDjxpo1wOM4dAOhaFiZgSYAvtxtAQ3AJwUGArXDEAA
---

:::{#example}
:::

:::{#relevant-functions}
:::

## Details

A file input allows you to upload one or more files.

To add a file input to your app:

  1. Add `ui.input_file()` to the UI of your app to create a file upload component. Where you call this function will determine where the date selector will appear within the app's layout.

  2. Specify the `id` and `label` parameters of `ui.input_date()` to define the identifier and label of the file upload.
    `ui.input_file()` also includes various optional parameters to control what kinds of files can be uploaded.

The value of an input component is accessible as a reactive value within the `server()` function.
The file input returns a list containing a dictionary of 4 keys:

  1. Use `input.<file_id>()` to access the value of the file input (e.g., `input.file()`). The server value of of the file input is a list containing a dictionary.

Here is an example of what the file input returns:

```python
[{'name': 'my_file.csv', 'size': 525600, 'type': 'text/csv', 'datapath': '/tmp/fileupload-8khw0q6n/tmpeobuc_pj/0.csv'}]
```

You will typically want to load the uploaded in your application,
to access the path of the uploaded file, you will first need to get the dictionary from the list, and get the value from the `'datapath'` key.
For example, `input.<file_id>()[0]['datapath']`.
