---
title: Checkbox Group
sidebar: components
appPreview:
  file: components/inputs/checkbox-group/app-preview.py
listing:
- id: example
  template: ../../_partials/_new_component-example.ejs
  template-params:
    dir: components/inputs/checkbox-group/
  contents:
  - title: Preview
    file: app-detail-preview.py
    height: 200
  - title: Express
    file: app-express.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQGJkAxASQA0BZAURQCU4B3AE4BLKsigBncRGScAHukFwJUjOgA6EAGaDSMZBIAWwiLmTCY6UoIrIAgpiJKIAEziCncAI5EArsM1NNQB9f2QAXmR-HCgAczhgrQAbfxcACk1kLKjhLBN0Xwpg4kM4YgBrACNSOWDY3V90NOQ6AB5WzOyu9TASsqqauoaNQhb2zq6snoBhUorquWR60kaeojaOmUmskDHN7e2eqB6UHrs1vYmDqbBKk+QegCELjavrnuJ7mZfxre2AX3Wvy6AEogftstEVhQCkUqHIKBkwAA3KApOA9MGaEGBVxwLQGdzI9xpfKFIjQ2FECTKCTCcggxBXAACzjcgiw8IoVzcBNR6LSjLe2SUFF8ghkFx6WAAVqQTKSILCsH15oNlo1BTiIEFMBF7Jg0iF-NSie5taMwBRcOgECgrXAEWB-gBdIA
  - title: Core
    file: app-core.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXZTmdKQYVkAQUxEG1ACZwGkuAEciAV04AdCJozoA+muQBeZGpxQA5nF10ANmukAKTchcnOWbuhUVdxdnGIAawAjUgAPXXMmFXQHZABiAB5E51c09TA-AJDwyOj0DKIklIg09LAAYX8g0LDkKNIYwoTk1LLkEBaS9vaMqAyUDNFm4raelwzggeQMgCER1tLx1wziaYyKhe6egF8ixbSASn3tl1NGii8fKjCKJzAANyg7OAzjzUPNTVk6NjkHuQOTzeIgXK5EVhwVisTjkQ6IMYAASkEFkDCwNwoYx+yCeLwc8LGaSkFBUDFKzQyWAAVqRuECIFcsFkarkGjECZ8tNBMEYxJgHDp9JwIf85FzCKgKLh0AgUGBMWAdgBdIA
- id: relevant-functions
  template: ../../_partials/components-detail-relevant-functions.ejs
  template-params:
    dir: components/inputs/checkbox-group/
  contents:
  - title: ui.input_checkbox_group
    href: https://shiny.posit.co/py/api/ui.input_checkbox_group.html
    signature: ui.input_checkbox_group(id, label, choices, *, selected=None, inline=False,
      width=None)
---

:::{#example}
:::

:::{#relevant-functions}
:::

## Details

A checkbox group creates a group of checkboxes that can be used to toggle multiple choices independently.

Follow these steps to display a checkbox group in your app:

  1. Add `ui.input_checkbox_group()` to the UI of your app to create a checkbox group. Where you call this function will determine where the checkbox group will appear within the app's layout.

  2. Specify the `id` and `label` parameters of `ui.input_checkbox_group()` to define the identifier and label of the checkbox group.

  3. Supply the `choices` parameter with either a list or dictionary of choices. If `choices` is a list, its elements become the select list values and labels. If `choices` is a dictionary, `ui.input_checkbox_group()` uses the dictionary keys as the checkbox values and the dictionary values as the checkbox labels.

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of a checkbox group:

  1. Use `input.<checkbox_group_id>()` (e.g., `input.checkbox_group()`) to access the value of a checkbox group. The server value of a checkbox group is a tuple of string(s) with the selected value(s).

See also: [Checkbox](../checkbox/index.qmd)
