---
title: "Action Link"
sidebar: components
previewapp: |
  from shiny import App, reactive, render, ui
  app_ui = ui.page_fluid(
      ui.input_action_link("action_link", "Action"),
      ui.output_text("counter"),
      {"class": "vh-100 d-flex justify-content-center align-items-center px-4"}
  )
  def server(input, output, session):
      @output
      @render.text()
      @reactive.event(input.action_link)
      def counter():
          return f""
  app = App(app_ui, server)
listing:
  id: component
  template: ../_partials/components-detail.ejs
  contents:
    - title: Action Link
      preview: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6cKITIcAbnAlSIAEzh0JAVw4AdCPrSoA+jqYBeJjqxQA5nGM0ANjtUAKfUy9WOGBgHcPCG8QnwwSFxgINwA2bV8uVC0yYxk5UmMnLgBrDxRZDgysiGzdfCYygEkIQikoFjgmADktGAAjDTKASi68T1CvawjW6Liw4mSklIoADzI8ki1yTrAujChVVWNCJ3qWPNUOFlRd7ABaAFYmdrOABm7e-oGQMp29ssQKsHk2M4BGW63JgAKy0LDkNHOJGW5DOhEoFDoTCgWVsEDOHAoMBYcIRGiYqBmlzKAF8+sFvGsNls3ix9mVZmRccs6N19F19Jy1HAaKwNIo6G5EskJBMyFMJA06YUIF1EE8mItyBZJNICooMAA1FFaOBuW4cgwUrwAATq6rgGAAojQaHBZAqzWq5Bq4IpyEKIFN1gUijlDSF1LzjG45QqQkqyBgGvNI6GmABqJh-Q2OlTqOgYRkKoOKiYs0Py42hKRkLR0YI0MogONdEllLmGdAqsSoNxGUwcSX8jSGsAkgC6QA
      height: 200px
      code: |
        from shiny import App, reactive, render, ui

        app_ui = ui.page_fluid(
            ui.input_action_link("action_link", "Action"), #<<
            ui.output_text("counter")
        )

        def server(input, output, session):
            @render.text()
            @reactive.event(input.action_link)
            def counter():
                return f"{input.action_link()}"

        app = App(app_ui, server)
      relevantfunctions:
        - title: ui.input_action_link
          href: https://shiny.posit.co/py/api/ui.input_action_link.html
          signature: ui.input_action_link(id, label, *, icon=None, **kwargs)
        - title: reactive.event
          href: https://shiny.posit.co/py/api/reactive.event.html
          signature: reactive.event(*args, ignore_none=True, ignore_init=False)

---

:::{#component}
:::

## Details

An action link appears as a link in your app and has a value that increments each time the user presses the link.

Follow these steps to add an action link to your app:

  1. Add `ui.input_action_link()` to the UI of your app to create an action link. Where you call this function will determine where the link appears within the app's layout.
  2. Specify the `id` and `label` parameters of `ui.input_action_link()` to define the action link's identifier and label.

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of an action link:

  1.  Use `input.<action_link_id()>` (e.g., `input.action_link()`) to access the value of the action link. The server value of an action link is an integer representing the number of clicks.

See also: [Action Button](action-button.qmd)
