---
title: "Action Button"
sidebar: components
previewapp: |
  from shiny import App, reactive, render, ui
  app_ui = ui.page_fluid(
      ui.input_action_button("action_button", "Action"),
      ui.output_text("counter"),
        {"class": "vh-100 d-flex justify-content-center align-items-center px-4"}
  )
  def server(input, output, session):
      @output
      @render.text()
      @reactive.event(input.action_button)
      def counter():
          return f""
  app = App(app_ui, server)
listing:
  - id: component
    template: ../_partials/components-detail.ejs
    contents:
      - title: Action Button
        preview: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6cKITIcAbnAlSIAEzh0JAVw4AdCPrSoA+jqYBeJjqxQA5nGM0ANjtUAKfUy9WOGBgHcPCG8QnwwSFxgINwA2bV8uVC0yYxk5UmMAI2SyUg8UWQ4M7LJcg3wmXTAASQhCKSgWOCYAOS0YTI0qgEpuvE9Qr2sI9ui4sOJkpJSKAA8yfJItci6wbowoVVVjQidGlnzVDhZUPewAWgBWJg7zgAYevoHBkCrd-arESrB5NnOARjudyYACstCw5DQLiQVuRzoRKBQ6EwoE4OLYIOcOBQYCx4YiNExULMrlUAL79YLedabbbvFgHKpzMj4lZ0Hr6br6blqOA0VgaRR0NyJZISSZkaYSJoMooQbqIZ5MJbkCySaSFRQYABqqK0cDcdy5BipXgAAg1NXAMABRGg0OCyJUWjVyLVwRTkEUQaYbQrFHKkY0hdT84xuBVKkIqsgYJoLGMRpgAaiY-2NzpU6joGGZStDysmbIjitNoSkZC0dGCNCqIET3TJVR5hnQarEqDcRlMHGlgo0xrAZIAukA
        height: 200px
        code: |
          from shiny import App, reactive, render, ui

          app_ui = ui.page_fluid(
            ui.input_action_button("action_button", "Action"), #<<
            ui.output_text("counter")
          )

          def server(input, output, session):
            @render.text()
            @reactive.event(input.action_button)
            def counter():
                return f"{input.action_button()}"

          app = App(app_ui, server)
        relevantfunctions:
          - title: ui.input_action_button
            href: https://shiny.posit.co/py/api/ui.input_action_button.html
            signature: ui.input_action_button(id, label, *, icon=None, width=None, **kwargs)
          - title: reactive.event
            href: https://shiny.posit.co/py/api/reactive.event.html
            signature: reactive.event(*args, ignore_none=True, ignore_init=False)

---

:::{#component}
:::

## Details

An action button appears as a button and has a value that increments each time the user presses the button.

Follow these steps to add an action button to your app:

  1. Add `ui.input_action_button()` to the UI of your app to create an action button. Where you call this function will determine where the button will appear within the app's layout.

  2. Specify the `id` and `label` parameters of `ui.input_action_button()` to define the button's identifier and label.

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of an action button:

  1. Use `input.<action_button_id()>` (e.g., `input.action_button()`) to access the value of the action button. The server value of an action button is an integer representing the number of clicks.

See also: [Action Link](action-link.qmd)



