---
title: Checkbox
sidebar: components
previewapp: |
  from shiny import App, render, ui
  app_ui = ui.page_fluid(
      ui.input_checkbox("x", "Checkbox Checkbox").add_class("mb-0"),
      ui.output_text_verbatim("txt"),
      {"class": "vh-100 d-flex justify-content-center align-items-center px-4"}
  )
  def server(input, output, session):
      @output
      @render.text
      def txt():
          return f""
  app = App(app_ui, server)
listing:
  - id: component
    template: ../_partials/components-detail.ejs
    contents:
      - title: Checkbox
        preview: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOtHQB9JUwC8TJVigBzOOpoAbJdIAUqpnb0cMDAO42I9jw4wkLMCFYA2RUcuVAUydUI2OEIAawAjYgAPGyJouMSk5XwmbIBhdITk7IkAFToFOABKDChpaUizKBYWVJh4gFoABiYKJLIOwkoKOmyqqolbTzt9HwU-QOCMYnCwiKVUgDcoCzgx2vrG5tbs9u7euH7B4bkxianpkGzCJpbsxFywTbYOgEYunoAKwULDIHBo2EGpAo5Gu5DkTB2HEMEA6HAoMBYcJGTFQSQ6AFZsgBfB5MKqqCkQVSyGisOSbORWULhCQrMhrCQsOAtDikKqIMkAASkEFkdAwSjJtKY212VgFZI8UjICjo7hZZG8hUyCtUaFQOlE6CsBs0HC5DLkVTAxIAukA
        height: 150px
        code: |
          from shiny import App, render, ui

          app_ui = ui.page_fluid(
              ui.input_checkbox("checkbox", "Checkbox", False), #<<
              ui.output_ui("value"),
          )

          def server(input, output, session):
              @render.ui
              def value():
                  return input.checkbox()

          app = App(app_ui, server)
        relevantfunctions:
          - title: ui.input_checkbox()
            href: https://shiny.posit.co/py/api/ui.input_checkbox.html#shiny.ui.input_checkbox
            signature: 'ui.input_checkbox(id: str, label: TagChild, value: bool = False, width: Optional = None)'
            github: https://github.com/posit-dev/py-shiny/blob/0e60bf8/shiny/ui/_input_check_radio.py#L32-L85
---

:::{#component}
:::

## Details

A checkbox creates a single checkbox that can be used to specify logical values. 

Follow these steps to add a checkbox to your app: 

  1. Add `ui.input_checkbox()` to the UI of your app to create a checkbox. Where you call this function will determine where the checkbox will appear within the app's layout. 
  
  2. Supply values to `ui.input_checkbox()`'s first two parameters (`id` and `label`) to specify the id and label of the checkbox. Optionally, set the `value` argument to either `True` or `False` to specify the initial value of the checkbox. By default, the checkbox has value `False` and is un-checked.  
  
The value of an input component is accessible as a reactive value within the `server()` function. To access the value of a checkbox:

  1. Use `input.<checkbox_id>()` (e.g., `input.checkbox()`) to access the value of a checkbox. The server value of a checkbox is `True` if checked and `False` if not checked. 
  
See also: Checkbox Group([Checkbox](checkbox.qmd)