---
title: Checkbox Group
sidebar: components
previewapp: |
  from shiny import App, render, req, ui
  app_ui = ui.page_fluid(
      ui.input_checkbox_group( 
          "checkbox_group", 
          "", 
          { 
              "a": "Watch me Whip", 
              "b": "Watch me Nae Nae", 
              "c": "Watch neither", 
          },
      ).add_class("mb-0"), 
      ui.output_text("value"),
        {"class": "vh-100 d-flex justify-content-center align-items-center px-4"}
  )
  def server(input, output, session):
      @output
      @render.text
      def value():
          return ""
  app = App(app_ui, server)
listing:
  - id: component
    template: ../_partials/components-detail.ejs
    contents:
      - title: Checkbox Group
        preview: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EqQEcJAVw4AdaOgD6apgF4marFADmcbTQA2a6QApNTJ0Y4YuqFWW2E2cQgGsAI2IAD21TBhVUOyZHZ3j1Il8A4LCI4ijEiTj4p0SAYWSg0KZ0zPxYiFznEErq6sSoRMRYsBEsuvqEsEDm1oAhDpyu1sI+gqGq+oBfbKmnAEo5+OMMsg8vChCyBzAANygbOESlzRBEwisoFhZx-bYAWgBGAAYXpmkH6zgQpkOOUwQB4cCgwFgPQiUCh0JioEIPAAsiWmmgWmlkNFYcj2cjs7k8EjWGwkLDgNw4pAWiGGAAEiZ5aVIILI6BgtmRhhimAcjnYqcN4lIyCo6FUhmAMAArYhcPEQDYYHx+YppSLRBZorSoAyidB2NCoXQcEnYuQLMDTAC6QA
        height: 200px
        code: |
          from shiny import App, render, req, ui

          app_ui = ui.page_fluid(
              ui.input_checkbox_group( #<<
                  "checkbox_group", #<<
                  "Checkbox group", #<<
                  { #<<
                      "a": "A", #<<
                      "b": "B", #<<
                      "c": "C", #<<
                  }, #<<
              ), #<<
              ui.output_text("value"),
          )

          def server(input, output, session):
              @render.text
              def value():
                  return ", ".join(input.checkbox_group())

          app = App(app_ui, server)
        relevantfunctions:
          - title: ui.input_checkbox_group
            href: https://shiny.posit.co/py/api/ui.input_checkbox_group.html#shiny.ui.input_checkbox_group
            signature: 'ui.input_checkbox_group(id: str, label: TagChild, choices: ChoicesArg, selected: Optional = None, inline: bool = False, width: Optional = None)'

            github: https://github.com/posit-dev/py-shiny/blob/0e60bf8/shiny/ui/_input_check_radio.py#L169-L237
---

:::{#component}
:::

## Details

A checkbox group creates a group of checkboxes that can be used to toggle multiple choices independently.

Follow these steps to display a checkbox group in your app:

  1. Add `ui.input_checkbox_group()` to the UI of your app to create a checkbox group. Where you call this function will determine where the checkbox group will appear within the app's layout.

  2. Specify the `id` and `label` parameters of `ui.input_checkbox_group()` to define the identifier and label of the checkbox group. 

  3. Supply the `choices` parameter with either a list or dictionary of choices. If `choices` is a list, its elements become the select list values and labels. If `choices` is a dictionary, `ui.input_checkbox_group()` uses the dictionary keys as the checkbox values and the dictionary values as the checkbox labels. 

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of a checkbox group:

  1. Use `input.<checkbox_group_id>()` (e.g., `input.checkbox_group()`) to access the value of a checkbox group. The server value of a checkbox group is a tuple of string(s) with the selected value(s). 

See also: [Checkbox](checkbox.qmd)