---
title: "Dark Mode Switch"
sidebar: components 
previewapp: |
  from shiny import ui, render, App
  app_ui = ui.page_fluid(
    ui.input_dark_mode().add_class("mb-0"), 
    {"class": "vh-100 d-flex flex-column justify-content-center align-items-center px-4"}
  )
  def server(input, output, session):
    pass
  app = App(app_ui, server)
listing:
  id: component
  template: ../_partials/components-detail.ejs
  contents:
    - title: Dark Mode Switch
      preview: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMArhzxM6lACZw6EgILoAOtHQB9MUwC8ojligBzOOpoAbMdIAUqpnoxdUIsuulQ6Aa3UxisqwEpVQIhVWRpWOQA3OStHZwliZycyCRY4FhYOUn9EWyZUKAy8u1U0VB0mJVQrMs1xCLpoun8wAF8AXSA
      height: 200px
      code: |
        from shiny import ui, render, App
        
        app_ui = ui.page_fluid(
            ui.input_dark_mode() #<<
        )
        
        def server(input, output, session):
            pass
        
        app = App(app_ui, server)
      relevantfunctions:
        - title: ui.input_dark_mode
          href: https://shiny.posit.co/py/api/ui.input_dark_mode.html
          signature: ui.input_dark_mode(id=None, mode=None, **kwargs)
---

:::{#component}
:::

## Details

A dark mode switch input toggles the app between dark and light modes.

To add a dark mode switch to your app:

  1. Add `ui.input_dark_mode()` to the UI of your app to create a dark mode switch. Where you call this function will determine where the dark mode switch will appear within the app's layout. 

  2. Optionally, specify the `id` parameter of `ui.input_dark_mode()` to define the identifier of the switch. When `id` is specified, you can use it to access the current color mode.

  3. By default, the user’s system settings for the preferred color scheme will be used for the initial mode of the app. To force the initial mode, set the `mode` parameter to `"light"` or `"dark"`. 

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of a dark mode switch:

  1. Use `input.<dark_mode_switch_id>()` (e.g., `input.mode()`) to access the value of the dark mode switch. The server value of a dark mode switch is a string: either `"light"` or `"dark"`.
