---
title: "Date Range Selector"
sidebar: components 
previewapp: |
  from shiny import App, render, ui

  app_ui = ui.page_fluid(
      ui.input_date_range("x", ""),
      ui.output_text_verbatim("txt"),
      {"class": "vh-100 d-flex justify-content-center align-items-center px-4"}
  )

  def server(input, output, session):
      @render.text
      def txt():
          return f""

  app = App(app_ui, server, debug=True)

listing:
  id: component
  template: ../_partials/components-detail.ejs
  contents:
    - title: Date Range Selector
      preview: |
        https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAEygrIEt4nvVi6ZVuzgAdCOPqMmAZwAWnCNl4x+gpgEF0eJnUos4dHQFdO48WlQB9U0wC8TU1igBzOFZoAbUywAU4pkDHTgxFVGMyKzYKKzooCDd-MGjDeLdRfCYMjJ0ZMihBOwyAJgAGMoBaUoBGKuqMgEoMKBYWK0JPKBkZJNQyCoBWJhgADwqoCOImChH+wkoKOka8AKCnYgjwyJmyJIA3KG8xMAaViCCLphAMjq6ZDMQssD25CurS0qYAK2M8zhpsBUSOQFkCFoYmIdOC4IBVOBQYDIwSC6ExUGMBhkAL7iJotNq3bpJGCAiZkKY7ZGLRrmCQQAw0WSGPaGXxhCI6DZkLa5ODdTikBqIVaBAACXK2IqYor09MMGB2UoZTAOR18QqlFz0ZGMdHONAyIHZZAwKTiCTg6uApQAuljplMjRAtqaRObEg1gNU7dk6RZ0PZNOhfJYbJxeXQWXQGmAsTagA
      height: 380px
      code: |
        from datetime import date
        
        from shiny import App, render, ui
        
        app_ui = ui.page_fluid(
            ui.input_date_range("daterange", "Date range", start="2020-01-01"), #<<
            ui.output_text("value"),
        )
        
        def server(input, output, session):
            @render.text
            def value():
                return f"{input.daterange()[0]} to {input.daterange()[1]}"
        
        app = App(app_ui, server)
      relevantfunctions:
        - title: ui.input_date_range
          href: https://shiny.posit.co/py/api/ui.input_date_range.html
          signature: ui.input_date_range(id, label, *, start=None, end=None, min=None, max=None, format='yyyy-mm-dd', startview='month', weekstart=0, language='en', separator=' to ', width=None, autoclose=True)

---

:::{#component}
:::

## Details

A date range selector allows you to select a pair of dates from two calendars. 

To add a date range selector to your app:

  1. Add `ui.input_date_range()` to the UI of your app to create a date range selector. Where you call this function will determine where the date range selector will appear within the app's layout. 

  2. Specify the `id` and `label` parameters of `ui.input_date_range()` to define the identifier and label of the daterange selector. `ui.input_date_range()` also includes various optional parameters, including `start` and `end`, which set the initial start and end dates.

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of a daterange selector:

  1. Use `input.<date_range_id>()` to access the value of a daterange selector (e.g., `input.daterange()`). The server value of a daterange selector is a tuple of date objects. You can access the individual tuple elements using square brackets and indices (e.g., `input.daterange()[0]`).


See also: [Date Selector](date-selector.qmd)
