---
title: Password Field
sidebar: components
previewapp: |
  from shiny import App, render, ui

  app_ui = ui.page_fluid(
      ui.input_password("x", "", placeholder="Enter password"),
      ui.output_text_verbatim("txt"),
      {"class": "vh-100 d-flex justify-content-center align-items-center px-4 flex-column"}
  )

  def server(input, output, session):
      @render.text
      def txt():
          return f''

  app = App(app_ui, server, debug=True)
listing:
  - id: component
    template: ../_partials/components-detail.ejs
    contents:
      - title: Password Field
        preview: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaAGyXSAFKqYODHDF1QKym1FBYsA7oNtlMC8ffzppIIkgyKYgmGwQvwCARiCASgwoaWlNQgtvFjtgsgBaAFYmGAAPEqh3YiYKKtLCSgo6dLx7R0NidzcPJo8ANzkAIygyPiLhqCs4Tu6HECC8gqDEWLBhthLkgAZ9pgArBRYpmmwSknI267a5JjmOYwgSjgoYFnvbuiZUGplIIAX1UGSyOTWPiK8Vq9UacGaP3a6VUaIgshorDkozoNlc7gkfTIAwkLDgPg4pDSiCWTAAAsSBnT6VIMXIMEM6ZimLN5jYaXTHJI4GQFHQILwIAMjKEAgL0ep0HpROgbBptBwyTi5GkwMCALpAA
        height: 200px
        code: |
          from shiny import App, render, ui

          app_ui = ui.page_fluid(
              ui.input_password("password", "Password", "mypassword1"), #<<
              ui.output_text_verbatim("value"),
          )

          def server(input, output, session):
              @render.text
              def value():
                  return input.password()

          app = App(app_ui, server)
        relevantfunctions:
          - title: ui.input_password
            href: https://shiny.posit.co/py/api/ui.input_password.html#shiny.ui.input_password
            signature: "ui.input_password(id: str, label: TagChild, value: str = '', width: Optional = None, placeholder: Optional = None)"

            github: https://github.com/posit-dev/py-shiny/blob/fb1e525/shiny/ui/_input_password.py#L12-L64
---

:::{#component}
:::

## Details

A password field creates a text box for password entry. 

To add a password field to your app:

  1. Add `ui.input_password()` to the UI of your app to create a password field. Where you call this function will determine where the password field will appear within the app's layout. 

  2. Specify the `id` and `label` parameters of `ui.input_password()` to define the identifier and label of the passsword field. `ui.input_password()` also includes various optional parameters, including `value`, which set the initial value.

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of a password field:

  1. Use `input.<password_field_id>()` (e.g., `input.password()`) to access the value of the password field. The server value of a password field is a string. 

