---
title: Selectize (Multiple)
sidebar: components
previewapp: |
  from shiny import App, Inputs, Outputs, Session, render, ui

  app_ui = ui.page_fluid(
    ui.input_selectize(
        "select",
        "",
        {
            "1": {"1A": "Choice 1A", "1B": "Choice 1B", "1C": "Choice 1C"},
            "2": {"2A": "Choice 2A", "2B": "Choice 2B", "2C": "Choice 2C"}
        },
        multiple=True
    ),
    ui.output_text("value"),
      {"class": "vh-100 d-flex justify-content-center align-items-center px-4"}
  )

  def server(input: Inputs, output: Outputs, session: Session):
      @output
      @render.text
      def value():
          return f""

  app = App(app_ui, server)
listing:
  - id: component
    template: ../_partials/components-detail.ejs
    contents:
      - title: Selectize (Multiple)
        preview: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaAGyXSAFKqYODHDF1QKymlnAtxCZDgBecDZMAMQAPOH2jjHKYF4+foFwcRIRURAxsWAAyt6+wsSo-qQsTABG3sQA7qlhkdFZTCBxAIwicYhMcQDCbMQchHBM7XVtAEKd3WB9A0Mjk-jTrT1Tvf2DwytxAL54jVkwChb+qD66ACp0CsPpBwCUaQ2ZjobE7m4eFAAeZHZgADcoFYUmBHqp7qpVLIaKw5AC5DZXO4JO8yJ8JF4WCwOKR7ogDgABKQQWR0DA-MgHGFMIEgmz4g4xKRkBR0TI0OIgZFkDAJArJBk7OJQ6DoPSidA2DTaDiY+Fye5gHYAXSAA
        height: 200px
        code: |
          from shiny import App, render, ui

          app_ui = ui.page_fluid(
              ui.input_selectize( #<<
                  "selectize", #<<
                  "Select options below:", #<<
                  {"1A": "Choice 1A", "1B": "Choice 1B", "1C": "Choice 1C"}, #<<
                  multiple=True #<<
              ), #<<
              ui.output_text("value"),
          )

          def server(input, output, session):
              @render.text
              def value():
                  return f"{input.selectize()}"

          app = App(app_ui, server)
        relevantfunctions:
          - title: ui.input_selectize
            href: https://shiny.posit.co/py/api/ui.input_selectize.html#shiny.ui.input_selectize
            signature: 'ui.input_selectize(id: str, label: TagChild, choices: SelectChoicesArg, selected: Optional = None, multiple: bool = False, width: Optional = None)'
            github: https://github.com/posit-dev/py-shiny/blob/a0df2ed/shiny/ui/_input_select.py#L48-L108
  - id: variations
    template: ../_partials/components-variations.ejs
    contents:
      variations:
        - title: Selectize with grouped choices
          description: To group the choices into categories, supply the `choices` argument with a dictionary of dictionaries. `ui.input_selectize()` will use the top-level keys as group labels.
          preview: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaAGyXSAFKqYODHDF1QKymlnAtxCZDgBecDZMAMQAPOH2jjHKYF4+foFwcRIRURAxsWAAyt6+wsSo-qQsTABG3sQA7oipYZHRWUwgDRnNzXEAjHGILd0ivUxxAMJsxByEcExdg-jDYF0AQkOj45PTy-XdI6tgYxNTM7tgAL5pjZkd2QBMQyBxN3N9a4fTT9tgNytICwcbTG+nxuJxe+3WRxBcVObSaWXOsKuzRgCgs-lQPl0ABU6Appuk4QBKC7tRyGYjuNweCgADzIdjAADcoFYUmBiapCapVLIaKw5Iy5DZXO4JBSyFSJF4WCwOKRCXUkUwAAJSCCyOgYWlkOG8pjM1k2BVwmJSMgKOiZGhxEAisgYBIFZJG05xbnQdB6UToGwabQcKUCuSEs4AXSAA
          code: |
            from shiny import App, render, ui

            app_ui = ui.page_fluid(
                ui.input_selectize( #<<
                    "selectize", #<<
                    "Select options below:", #<<
                    { #<<
                        "1": {"1A": "Choice 1A", "1B": "Choice 1B", "1C": "Choice 1C"}, #<<
                        "2": {"2A": "Choice 2A", "2B": "Choice 2B", "2C": "Choice 2C"} #<<
                    }, #<<
                    multiple=True #<<
                ), #<<
                ui.output_text("value"),
            )

            def server(input, output, session):
                @render.text
                def value():
                    return f"{input.selectize()}"

            app = App(app_ui, server)
---

:::{#component}
:::

## Details

A selectize list creates a way to select one or more items from a list.

To use a selectize list that allows you to select <em>multiple</em> items: 

  1. Add `ui.input_selectize()` to the UI of your app to create a selectize list. Where you call this function will determine where the selectize list appears within the app's layout. 

  2. Specify the `id` and `label` parameters of `ui.input_selectize()` to define the identifier and label of the select list.

  3. Supply the `choices` parameter with either a list or dictionary of choices. If `choices` is a list, its elements become the select list values and labels. If `choices` is a dictionary, `ui.input_selectize()` uses the dictionary keys as the list values and the dictionary values as the list labels. 
  
  You can also supply with `choices` a dictionary of dictionaries. `ui.input_selectize()` will use the top-level keys as group labels. See <em>Selectize with grouped choices</em> variation.

  4. The `multiple` parameter controls whether you can select multiple items at once. Set `multiple=True` to allow the user to select multiple values.

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of a selectize list:

  1. Use `input.<selectize_id>()` (e.g., `input.selectize()`) to access the selected value(s). The server value of a selectize list is a list of strings.

See also: [Selectize (Single)](selectize-single.qmd) and [Select (Multiple)](select-multiple.qmd). Select inputs and selectize inputs are similar, but have different interfaces and provide different ways of selecting multiple options. Selectize inputs also allow you to deselect items.

:::{#variations}
:::