---
title: "Slider"
sidebar: components 
previewapp: |
  from shiny import App, render, ui

  app_ui = ui.page_fluid(
      ui.input_slider("x", "", min=0, max=20, value=10),
      ui.output_text_verbatim("txt"),
      {"class": "vh-100 d-flex justify-content-center align-items-center px-4"}
  )

  def server(input, output, session):
      @render.text
      def txt():
          return f""

  app = App(app_ui, server, debug=True)
listing:
  id: component
  template: ../_partials/components-detail.ejs
  contents:
    - title: Slider
      preview: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMArhzxM6lACZw6EgILoAOhFVpUAfTFMAvKI5YoAcziaaAGzHSAFKqYODGLqhFlNLCx1l07YT95yyvhMwcESAAwSAIwRUUwArBEAlBhQ0tKahBZQLCx+qGQAtAlMMAAeRVBuxEwU5cWElBR0wcl49o5iGMRuru717gBucgBGUGR8fkNQVnBtHRCOTCDB2bkswYihYENsRbERTABWIiyTNNhFJOTN181yTLMcxhBFHBQwLPe3dEyolQSwQAvqpUulMus8n4YFdqmRaoMfi02qpVLIaKw5CNfC43BJemR+hIWHA8hxSMlEJ0HAABQn9GlMWlSCA+DCDJkYpgzOY2KlM5ZSMgiOhLGjBEB4sgYAI+fmgsBo6DoPRMJSoGwabTiLF0HHJMDAgC6QA
      height: 200px
      code: |
        from shiny import ui, render, App
        
        app_ui = ui.page_fluid(
            ui.input_slider("slider", "Slider", 0, 100, 50), #<<
            ui.output_text_verbatim("value"),
        )
        
        def server(input, output, session):
            @render.text
            def value():
                return f"{input.slider()}"
        
        app = App(app_ui, server)
      relevantfunctions:
        - title: ui.input_slider
          href: https://shiny.posit.co/py/api/ui.input_slider.html
          signature: ui.input_slider(id, label, min, max, value, *, step=None, ticks=False, animate=False, width=None, sep=',', pre=None, post=None, time_format=None, timezone=None, drag_range=True)
---

:::{#component}
:::

## Details

A slider is a widget that lets you drag to select a number, date, or date-time from a specified range. 

To add a slider to your app:

  1. Add `ui.input_slider()` to the UI of your app to create a slider. Where you call this function will determine where the slider will appear within the app's layout. 

  2. Specify the `id` and `label` parameters of `ui.input_slider()` to define the identifier and label of the slider. 

  3. Use the `min` and `max` parameters to define the minimum and maximum values of the slider. 

  4. Set the `value` parameter to define the starting slider value. `min`, `max`, and `value` can be numbers, dates, or date-times. Dates and date-times can be provided from the `datetime` module with the `date()` or `datetime()` functions, respectively.

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of a slider:

  1. Use `input.<slider_id>()` (e.g., `input.slider()`) to access the value of the slider. The server value of a slider is a number, date, or date-time (depending on the class of `value`). 

See also: [Slider Range](slider-range.qmd)
