---
title: Text Box
sidebar: components
previewapp: |
  from shiny import App, render, ui

  app_ui = ui.page_fluid(
      ui.input_text("x", "", placeholder="Enter text"),
      ui.output_text_verbatim("txt"),
      {"class": "vh-100 d-flex justify-content-center align-items-center px-4"}
  )

  def server(input, output, session):
      @render.text
      def txt():
          return f''

  app = App(app_ui, server, debug=True)
listing:
  - id: component
    template: ../_partials/components-detail.ejs
    contents:
      - title: Text Box
        preview: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMArhzxM6lACZw6EgILoAOhFVpUAfTFMAvKI5YoAcziaaAGzHSAFKqYODGLqhFlNFAB5k7YL2WV8JkDAiUCAUXI5Jn8MOMCASgwoaWlNQgsoFhZfVDIAWgBWJhhPfKg3Yhi4b3zCSgo6RLx7RzEMYjdXd39NADc5ACMoMj5fPqgrOGbWhxBAjKyWQMRgsD62fIBGAAYdpgArERZRmmw60gpyOoboyY5jCHyOChgWG6i6JlQywsCAX1USRSaUW2V8MHOFTIVX8H0aiVUqlkNFYcgGdBsLjcEk6ZG6EhYcGyHFICUQsyYAAE8d1KVSpBBZHQMP5KSimBMpjZyZTHJI4GQRHQILwIN1WTUfAkkdB0HomEpUDYNNpxGi6BiEmB-gBdIA
        height: 200px
        code: |
          from shiny import ui, render, App

          app_ui = ui.page_fluid(
              ui.input_text("text", "Text input", "Enter text..."), #<<
              ui.output_text_verbatim("value"),
          )

          def server(input, output, session):
              @render.text
              def value():
                  return input.text()

          app = App(app_ui, server)
        relevantfunctions:
          - title: ui.input_text
            href: https://shiny.posit.co/py/api/ui.input_text.html#shiny.ui.input_text
            signature: "ui.input_text(id: str, label: TagChild, value: str = '', width: Optional = None, placeholder: Optional = None, autocomplete: Optional = 'off', spellcheck: Optional = None)"
            github: https://github.com/posit-dev/py-shiny/blob/a0df2ed/shiny/ui/_input_text.py#L13-L80
---

:::{#component}
:::

## Details

Create input control for entry of text values.

To add a text box to your app:

  1. Add `ui.input_text()` to the UI of your app to create a text box. Where you call this function will determine where the text box will appear within the app's layout. 

  2. Specify the `id` and `label` parameters of `ui.input_text_area()` to define the identifier and label of the text box. 

  3. By default, the `value` parameter, which defines the text box's initial value, is the empty string (`''`). Provide a different string to `value` to change the initial text.

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of a text box:

  1. Use `input.<text_id>()` (e.g., `input.text()`) to access the value of the text box. The server value of a text box is a string containing the current text input.
        
See also: [Text Area](text-area.qmd)