---
title: Text Area
sidebar: components
previewapp: |
  from shiny import App, render, ui

  app_ui = ui.page_fluid(
      ui.input_text_area("x", "", placeholder="Enter text"),
      ui.output_text_verbatim("txt"),
      {"class": "vh-100 d-flex justify-content-center align-items-center px-4"}
  )

  def server(input, output, session):
      @render.text
      def txt():
          return f''

  app = App(app_ui, server, debug=True)
listing:
  - id: component
    template: ../_partials/components-detail.ejs
    contents:
      - title: Text Area
        preview: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMArhzxM6lACZw6EgILoAOhFVpUAfTFMAvKI5YoAcziaaAGzHSAFKqYODGLqhFlNFAB7uoUqHbAvMl84KGV8JnDwiXCACTgLC2ImAHVBC2lwgEoMKGlpTUILKBYWANQyAFoAViYYT0qoN2SgysJKCjpsvHtHMQxiN1d3IM0ANzkAIygyPgCxqCs4bt6HEHCikpZwxEiwMbZKgEYABhOmACsRFlmabDbSCnI2jrkmRY5jCEqOChgWF7kN6oBrVcIAX1UOTyBU2pQCMHuTTILTg3kBnWyqlUshorDkEzoNhcbgkgzIwwkLDgpQ4pCyiFWTAAAlIILI6BggkzcUwFksbAymY5JHAyCI6BBeBBhly0cE-ILsdB0HomEpUDYNNpxPi6ISsqowOCALpAA
        height: 200px
        code: |
          from shiny import ui, render, App

          app_ui = ui.page_fluid(
              ui.input_text_area("textarea", "Text input", "Hello World"), #<<
              ui.output_text_verbatim("value"),
          )

          def server(input, output, session):
              @render.text
              def value():
                  return input.textarea()

          app = App(app_ui, server)
        relevantfunctions:
          - title: ui.input_text_area
            href: https://shiny.posit.co/py/api/ui.input_text_area.html#shiny.ui.input_text_area
            signature: "ui.input_text_area(id: str, label: TagChild, value: str = '', width: Optional = None, height: Optional = None, cols: Optional = None, rows: Optional = None, placeholder: Optional = None, resize: Optional = None, autoresize: bool = False, autocomplete: Optional = None, spellcheck: Optional = None)"
            github: https://github.com/posit-dev/py-shiny/blob/0e60bf8/shiny/ui/_input_text.py#L83-L187
---

:::{#component}
:::

## Details

Create a textarea input control for entry of unstructured text values.

To add a textarea to your app:

  1. Add `ui.input_text_area()` to the UI of your app to create a textarea. Where you call this function will determine where the textarea will appear within the app's layout. 

  2. Specify the `id` and `label` parameters of `ui.input_text_area()` to define the identifier and label of the textarea. 

  3. By default, the `value` parameter, which defines the textarea's initial value, is the empty string (`''`). Provide a different string to `value` to change the initial text.


The value of an input component is accessible as a reactive value within the `server()` function. To access the value of a textarea:

  1. Use `input.<textarea_id>()` (e.g., `input.textarea()`) to access the value of the textarea. The server value of a textarea is a string containing the current text input.

See also: [Text Box](text-box.qmd)
