---
title: Select (Multiple)
sidebar: components
appPreview:
  file: components/inputs/select-multiple/app-preview.py
listing:
- id: example
  template: ../../_partials/_new_component-example.ejs
  template-params:
    dir: components/inputs/select-multiple/
  contents:
  - title: Preview
    file: app-detail-preview.py
    height: 200
  - title: Express
    file: app-express.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQGJkAxASQA0BZAURQCU4B3AE4BLKsigBncRGScAHukFwJUjOgA6EAGaDSMZBIAWwiLmTCY6UoIrIAgpiJKIAEziCiAV2GbNagPreyAC8yN44UADmcP5aADbeLgAUmshhwlgm6J4U-hJwcXDEFEnIdAA85alpNWnqYPmFxfVEFVUytTX1AMoFRbak6BTC5FIARgWk-IgtZZXVncgg9QCMdvUo9QDChqTCxHDIa7OrAEIbyNu7+4cr54SXYCtbF1d7B0cvYAC+rfMdixgnjiw3QhWCABVBJ5Dm0FsgAJR-dq1cKkHLZXJUOQleoANygCTg9SRmgRvlccC0BncePcSSyOSI6IomKI+RUIwgCJmHQAAs43IIsNiKPC3NSCUSkjz4bUlBRPIIZFp6iBGRQsI1+jLvvUKWoQvZMEkAt52bT3OSIA8wBRcOgECg7XAcT8ALpAA
  - title: Core
    file: app-core.py
    shinylive: https://shinylive.io/py/editor/#code=NobwRAdghgtgpmAXAAjFADugdOgnmAGlQGMB7CAFzkqVQDMAnUmZAZwAsBLCXZTmdKQYVkAQUxEG1ACZwGRAK6cAOhFUZ0AfSXIAvMiU4oAczia6AGyXSAFKuQHOWbugUVNrOBbjEKN5ADEADxB9g7hDspgnt6+UUTBoRAREVEAyl4+IqToFJzkrMgARl6kAO6I8YEhYSnIIFEAjKJRKFEAwuyknMRwyM1VTQBCrcgdXT19jSOEY2CN7aPj3b39i2AAvgk1yXXIMAoWeejeugAqDAp9ibXIAJTbSRGGpG6u7lQAHn5RAG5QVjgUQeqjuqlUsjobDkvzkNhcbiIrwo7yInlYrHyEDulV2AAEpBBZAwsF8KLdIch-oCbDjbhEpBQFAxknQoiAERQsDEsrSNlFwdBMHoxJgbBptJw0TC5GCILMwBRcOgEChFXBvpsALpAA
- id: relevant-functions
  template: ../../_partials/_new_relevant-functions.ejs
  template-params:
    dir: components/inputs/select-multiple/
  contents:
  - title: ui.input_select
    href: https://shiny.posit.co/py/api/ui.input_select.html
    signature: ui.input_select(id, label, choices, *, selected=None, multiple=False,
      selectize=False, width=None, size=None)
- id: variations
  template: ../../_partials/_new_variations.ejs
  template-params:
    dir: components/inputs/select-multiple/
  contents:
  - title: Select list with grouped choices
    description: To group the choices into categories, supply the `choices` argument
      with a dictionary of dictionaries. `ui.input_select()` will use the top-level
      keys as group labels.
    apps:
    - title: Express
      file: app-variation-select-list-with-grouped-choices-express.py
      shinylive: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaAGyXSAFKqYODHDF1QKymlnAtxCZG0wAxAA8wfaOEcpgXj5+URIhYRARkWAAyt6+wsSoZBykLEwARt7EAO6I8UGh4SlMINVJdXVRAIxRiPVtIh1MUQDCbMQchHBMrT34fWCtAEK9A0MjY3NVbf0LYIPDo+MbYAC+CTXJzakATL0gUeeTnYs7Y7drYOfzSNPby0xvL+f79y2S12-yiB0atRSRwhpzqMAUFjyqB8ugAKnQFGNEpCAJTHJqOQzEdxuDwUAAe-iiADcoFY4FE8aocapVLIaKw5NS5DZXO4JMSyKSJF4WCx8hAcZVYUwAAJSCCyOgYClkSHspi0+k2KWQiJSMgKOjJGhREB8sgYGJZHUHKKs6DoPSidA2DTaDgirlyHGHAC6QA
    - title: Core
      file: app-variation-select-list-with-grouped-choices-core.py
      shinylive: https://shinylive.io/py/app/#h=0&code=NobwRAdghgtgpmAXGKAHVA6VBPMAaMAYwHsIAXOcpMAMwCdiYACAZwAsBLCbJjmVYnTJMAgujxM6lACZw6EgK4cAOhFVpUAfSVMAvEyVYoAcziaaAGyXSAFKqYODHDF1QKymlnAtxCZG0wAxAA8wfaOEcpgXj5+URIhYRARkWAAyt6+wsSoZBykLEwARt7EAO6I8UGh4SlMINVJdXVRAIxRiPVtIh1MUQDCbMQchHBMrT34fWCtAEK9A0MjY3NVbf0LYIPDo+MbYAC+CTXJzakATL0gUeeTnYs7Y7drYOfzSNPby0xvL+f79y2S12-yiB0atRSRwhpzqMAUFjyqB8ugAKnQFGNEpCAJTHJqOQzEdxuDwUAAe-iiADcoFY4FE8aocapVLIaKw5NS5DZXO4JMSyKSJF4WCx8hAcZVYUwAAJSCCyOgYClkSHspi0+k2KWQiJSMgKOjJGhREB8sgYGJZHUHKKs6DoPSidA2DTaDgirlyHGHAC6QA
---

:::{#example}
:::

:::{#relevant-functions}
:::

## Details
A select list creates a way to select one or more items from a list.

To add a select list that allows you to select <em>multiple</em> items to your app:

  1. Add `ui.input_select()` to the UI of your app to create a select list. Where you call this function will determine where the select list appears within the app's layout.

  2. Specify the `id` and `label` parameters of `ui.input_select()` to define the identifier and label of the select list.

  3. Supply the `choices` parameter with either a list or dictionary of choices. If `choices` is a list, its elements become the select list values and labels. If `choices` is a dictionary, `ui.input_select()` uses the dictionary keys as the list values and the dictionary values as the list labels.

  You can also supply with `choices` a dictionary of dictionaries. `ui.input_selectize()` will use the top-level keys as group labels. See <em>Selectize with grouped choices</em> variation.

  4. Set the `multiple` parameter to `True` to allow the user to select multiple items at once. By default, `multiple` is `False`.

The value of an input component is accessible as a reactive value within the `server()` function. To access the value of a select list:

  1. Use `input.<select_id>()` (e.g., `input.select()`) to access the selected value(s). The server value of a select list is a list of strings.

See also: [Select (Single)](select-single.qmd) and [Selectize (Multiple)](selectize-multiple.qmd). Select inputs and selectize inputs are similar, but have different interfaces and provide different ways of selecting multiple options. Selectize inputs also allow you to deselect items.

:::{#variations}
:::
