---
title: Debug, troubleshoot, & help
---

## Common issues

Before jumping into general debugging techniques, lets cover some common issues that you may encounter when developing Shiny applications, and explain why they happen.

### Missing output

Sometimes, output won't appear at all.
This most commonly happens when an output reads a non-existent input, for example:

```{shinylive-python}
#| standalone: true
#| components: [editor, viewer]
#| layout: vertical
#| viewerHeight: 120

from shiny.express import input, render, ui

ui.input_slider("val", "Slider value", min=0, max=10, value=5)

# Nothing renders because input.wrong_id() doesn't exist!
@render.text
def slider_val():
    return f"Slider value: {input.wrong_id()}"
```

This happens because, if a non-existent input is read, a [`SilentException`](/api/express/req.html#shiny) is raised.
That behavior is useful for events and [dynamic ui](/docs/ui-dynamic.qmd), but it can be confusing when you mistype an input id.

### Output errors

When an error occurs inside a `render` decorator function, the relevant error message is displayed in red font where the output would normally be located, for example:

```{shinylive-python}
#| standalone: true
#| components: [editor, viewer]
#| layout: vertical
#| viewerHeight: 120
from shiny.express import render

@render.text
def good():
    return "This output is fine, but the next one is not."

@render.text
def bad():
    return str(a_missing_variable)
```

The error displayed in the app is only the final part of the stack trace, but the full trace can be read in the console where you used `shiny run`.

::: callout-note
## Sanitized error messages

When Shiny apps are deployed, error messages are sanitized to the eliminate the possibility of leaking sensitive information.
To unsanitize error messages, you'll need to set `sanitize_errors=False` in the `App` constructor (of a [Shiny core app](/docs/express-vs-core.qmd)).
:::

## Debugging

### Print statements

A quick and simple way to debug Shiny applications is to add `print()` statements.
This lets you see the value of different variables, and how they change when you toggle different inputs.

::: callout-warning
If your Shiny application is running with Shinylive (Python in the browser), and there is not a visible Python console, then error messages will show up in your browser's JavaScript console.
:::

### Positron and VS Code debugger

The [VS Code debugger](https://code.visualstudio.com/docs/editor/debugging) is a powerful tool for debugging Python code.

### Breakpoints {#breakpoints}

You can use `breakpoint()` to pause your app while it's running and inspect what's going on.
This lets you debug using the built-in [Python debugger (pdb)](https://docs.python.org/3/library/pdb.html).

```python
@render.text
def bad():
    breakpoint()
    return str(a_missing_variable)
```

When Python hits the `breakpoint()`, it will pause and open the debugger in your terminal.

From there, you can run commands like:

- `continue`: resume running the app
- `exit` or <kbd>Ctrl</kbd> + <kbd>D</kbd>: exit the debugger and stop the app

This is helpful for figuring out where things go wrong in your code.


### Shiny debug mode

An advanced option for debugging [Shiny Core apps](/docs/express-vs-core.qmd) is using the `App(..., debug=True)` argument.

When you run a Shiny app in debug mode, you'll see detailed messages in the terminal.
These messages show the communication between the server and the web browser.

This is an example of the raw data behind how your app works:

```json
SEND: {"busy": "busy"}
SEND: {"recalculating": {"name": "my_cool_output", "status": "recalculating"}}
SEND: {"recalculating": {"name": "my_cool_output", "status": "recalculated"}}
SEND: {"busy": "idle"}
SEND: {"values": {}, "inputMessages": [], "errors": {}}
```

- When a user changes an input, the browser sends a message to the server.
- The server responds with updates, like re-running a calculation or updating a plot.

Note also that Shiny applications use Python's [asyncio](https://docs.python.org/3/library/asyncio.html) under the hood, so it may be useful to set
[asyncio's debug mode](https://docs.python.org/3/library/asyncio-dev.html#debug-mode).


## Get Help

### Shiny

  1. The first place to look for help with Shiny is [Posit Community](https://community.rstudio.com/c/shiny){target="_blank"}, which is a warm and welcoming place to ask any questions you might have about Shiny (as well as tidyverse and all things Posit). The web site is running Discourse, which is an excellent community discussion platform. Our developers monitor Posit Community and answer questions periodically.

  2. Shiny users (and the Shiny team!) regularly talk on [Shiny's Discord server](https://discord.gg/yMGCamUMnS){target="_blank"}. Discord has more of a chat interface than Posit Community, and is not indexed by search engines. It's a great forum for casual conversations or networking with other Shiny developers.

  3. You can also check the ["shiny+python" tag on Stack Overflow](https://stackoverflow.com/questions/tagged/shiny+python){target="_blank"} for existing answers, or post your own question. (Keep in mind that general [Shiny for R answers](https://stackoverflow.com/questions/tagged/shiny){target="_blank"} may also point you in the right direction.) Note that questions posted on Stack Overflow are not closely monitored by our developers.

### Posit Connect Cloud

  1. For information about [Posit Connect Cloud](https://connect.posit.cloud/), see the [Connect Cloud Documentation](https://docs.posit.co/connect-cloud/){target="_blank"}
  2. For community support, there is a [community forum for Connect Cloud](https://forum.posit.co/c/posit-professional-hosted/posit-connect-cloud/67){target="_blank"}.

  3. Customers with Starter, Basic, Standard or Pro subscriptions can get direct access to our support engineers by opening a case on [the Posit Support site](https://support.posit.co/?_gl=1*1aff1iz*_ga*MjQzNjU5NDUuMTY0ODgyOTc5Ng..*_ga_2C0WZ1JHG0*MTY5MTQ0NjYwNy41LjAuMTY5MTQ0NjYwOS4wLjAuMA..*_ga_HXP006LBGY*MTY5MTQ0NjYwNy41LjAuMTY5MTQ0NjYwOS4wLjAuMA..){target="_blank"}. Questions are answered from 9AM - 5PM(EST) Monday - Friday.

### shinyapps.io

  1. For documentation and instructions on how to use [shinyapps.io](http://shinyapps.io){target="_blank"}, see the [shinyapps.io user guide](https://docs.posit.co/shinyapps.io/?_gl=1*fwm1mn*_ga*MjQzNjU5NDUuMTY0ODgyOTc5Ng..*_ga_HXP006LBGY*MTY5MTQ0NjYwNy41LjAuMTY5MTQ0NjYwOS4wLjAuMA..){target="_blank"}.

  2. The best place to get community support for shinyapps.io is the [shinyapps.io category on Posit Community](https://community.rstudio.com/tags/shinyappsio?_gl=1*nqeupu*_ga*MjQzNjU5NDUuMTY0ODgyOTc5Ng..*_ga_2C0WZ1JHG0*MTY5MTQ0NjYwNy41LjAuMTY5MTQ0NjYwOS4wLjAuMA..*_ga_HXP006LBGY*MTY5MTQ0NjYwNy41LjAuMTY5MTQ0NjYwOS4wLjAuMA..){target="_blank"}. If you're having difficulties with shinyapps.io, feel free to ask questions there. Another option is to file an issue in the [rsconnect-python package repo](https://github.com/rstudio/rsconnect-python/issues){target="_blank"}.

  3. Customers with Starter, Basic, Standard or Pro subscriptions can get direct access to our support engineers by opening a case on [the Posit Support site](https://support.posit.co/?_gl=1*1aff1iz*_ga*MjQzNjU5NDUuMTY0ODgyOTc5Ng..*_ga_2C0WZ1JHG0*MTY5MTQ0NjYwNy41LjAuMTY5MTQ0NjYwOS4wLjAuMA..*_ga_HXP006LBGY*MTY5MTQ0NjYwNy41LjAuMTY5MTQ0NjYwOS4wLjAuMA..){target="_blank"}. Questions are answered from 9AM - 5PM(EST) Monday - Friday.


### Posit Connect and Shiny Server Pro

Customers with Posit Connect or Shiny Server Pro subscriptions can [contact our dedicated support team](https://support.posit.co/){target="_blank"} for our commercial offerings.

### Sales

For sales questions, please email [sales@posit.co](mailto:sales@posit.co).
