---
title: Hosting and deployment
description: When it's time to put your Shiny app on the web, you can choose to deploy on your own servers or on our hosting service.
aliases:
  - /docs/deploy.html
---

:::{.lead}
When it's time to put your Shiny app on the web, you can choose to deploy on your own servers or on our hosting service.
:::


## Cloud hosting

The easiest deployment option to get started with is cloud hosting.
Since you don't need to run your own server, you can have your Shiny app up and running in minutes!

Shiny cloud hosting may not be right for you if your app must run within your datacenter or virtual private cloud; please see the next option if that's the case.

<a class="btn btn-outline-dark btn-sm mt-3 no-icon" href="deploy-cloud.qmd">Learn more</a>

## Self-hosted deployments

If you prefer to run your own server, or you must run your apps inside your network or virtual private cloud, then a self-hosted (or on-premises) deployment may be right for you.
Posit offers both open source (Shiny Server) and commercial/enterprise (Posit Connect) options for Shiny app hosting.

<a class="btn btn-outline-dark btn-sm mt-3 no-icon" href="deploy-on-prem.qmd">Learn more</a>

## Static hosting

Some Shiny apps can be converted into completely static web pages (HTML, CSS, and JavaScript), with no need for Python to be running on the server.
This is made possible by running the Shiny app's Python logic entirely inside of the browser, using the magic of WebAssembly.
We call this mode ShinyLive, and it has great benefits for making hosting cheaper, simpler, and practically infinitely scalable.

<a class="btn btn-outline-dark btn-sm mt-3 no-icon" href="shinylive.qmd">Learn more</a>

## More resources

See [a comparison of Posit's hosting and deployment options for Shiny](https://posit.co/products/open-source/shinyserver/).
If you have any questions about which product is the right fit for you, please email <a href="mailto:sales@posit.co">sales@posit.co</a>.
