---
title: "Cloud hosting"
---

## Posit Connect Cloud

The quickest way to get started is [Posit Connect Cloud](https://connect.posit.cloud/), our next-generation online publishing platform. 

You can deploy Shiny applications - and other data frameworks - from GitHub to Connect Cloud in under a minute. All you need is your code and a requirements.txt dependency file. 

Quickly showcase your work with a public portfolio and leverage powerful features such as secret environment variable management and automatic push-to-publish for seamless continuous deployment. Free and paid plans are available.

To get started, sign up for [Connect Cloud](https://connect.posit.cloud/), review the [how-to guide](https://docs.posit.co/connect-cloud/how-to/python/shiny-python.html), and join the [community](https://forum.posit.co/c/posit-professional-hosted/posit-connect-cloud/67).


## Shinyapps.io

[shinyapps.io](https://www.shinyapps.io/) also allows you to easily host applications without having to set up your own server, and has a variety of free and paid plans depending on your use case.

To use shinyapps.io, follow these steps:

1. Install the [rsconnect-python](https://github.com/rstudio/rsconnect-python) package.

    ```bash
    pip install rsconnect-python
    ```

    Deploying [Shiny Express](https://shiny.posit.co/blog/posts/shiny-express/) applications requires version 1.22.0 or later of the [rsconnect-python package](https://github.com/rstudio/rsconnect-python).

2. [Sign up](https://www.shinyapps.io/admin/#/signup) for a free shinyapps.io account

3. When you log in for the first time, you will be shown a command to run that will [configure rsconnect-python](https://docs.posit.co/shinyapps.io/getting-started.html#configure-rsconnect-python) with a shinyapps.io API token. The command will look something like:

    ```bash
    rsconnect add --account <ACCOUNT> --name <NAME> --token <TOKEN> --secret <SECRET>
    ```

4. Deploy your application by calling `rsconnect deploy`.

    ```bash
    rsconnect deploy shiny /path/to/app --name <NAME> --title my-app
    ```

After following these steps you will be able to manage and share the application on the cloud.
Please see the [full documentation](https://docs.posit.co/shinyapps.io/getting-started.html#configure-rsconnect-python) for more information on how to deploy content to shinyapps.io.

## Hugging Face

Hugging Face is an open-source platform that provides state-of-the-art natural language processing (NLP) tools and models.
You can host a variety of applications, including Shiny apps, on Hugging Face using [Hugging Face spaces](https://huggingface.co/spaces) which makes it easy to integrate their hosted models into your Shiny app without having to build everything from scratch.
Hugging Face has implemented [templated spaces](https://huggingface.co/new-space?template=posit/shiny-for-python-template) for Shiny applications which will populate all the files you need to get started.

