---
title: "Customizing UI"
editor: visual
---

This article covers various levels of ways of customizing the overall look and feel of your Shiny app.

:::{.callout-tip}
#### Customizing components

The techniques covered here are intentionally generic (i.e., applies to all UI). Some components may have additional customization options (e.g., `ui.sidebar()` has a `bg` argument to change the background color).
:::


## Shinyswatch

The [shinyswatch](https://github.com/posit-dev/py-shinyswatch) package makes is very easy to change the look of your app, and provides over a dozen different [bootswatch](https://bootswatch.com/) themes to choose from.
Simply choose a theme and add `shinyswatch.theme.<theme_name>()` anywhere in the UI.

``` {shinylive-python}
#| standalone: true
#| components: [editor, viewer]
#| layout: vertical
#| viewerHeight: 200

from shiny import App, render, ui
from shinyswatch import theme

app_ui = ui.page_sidebar(
    ui.sidebar("Sidebar content"),
    "Main content",
    theme.darkly(),
    title = "Hello darkly theme"
)

app = App(app_ui, None)
## file: requirements.txt
shinyswatch
```

## Custom CSS

If you want to customize the look of your app beyond what is available in shinyswatch, a natural next step is to add custom CSS. This is pretty straightforward to do since [UI components are HTML](#ui-is-html). That said, you'll at least want to know the basics of CSS, including [CSS selectors](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors) before you get started.


### CSS string

If you don't need much CSS, you can add a string of CSS directly to your UI with `ui.tags.style()`. This is convenient because you don't need to create an external file, but it can be a bit cumbersome if you have a lot of CSS.

``` {shinylive-python}
#| standalone: true
#| components: [editor, viewer]
#| layout: vertical
#| viewerHeight: 150

from shiny import App, ui

app_ui = ui.page_fixed(
    ui.tags.style(
        ".card-header { background:#2A2A2A; color:white }"
    ),
    ui.card(
        ui.card_header("Card header"),
        "Card body"
    )
)

app = App(app_ui, None)
```

### CSS file

If you have a lot of CSS, put it in an external file and import it with `ui.include_css()`.

``` {shinylive-python}
#| standalone: true
#| components: [editor, viewer]
#| layout: vertical
#| viewerHeight: 150

from pathlib import Path
from shiny import App, ui

app_ui = ui.page_fixed(
    ui.include_css(
        Path(__file__).parent / "my-styles.css"
    ),
    ui.card(
        ui.card_header("Card header"),
        "Card body"
    )
)

app = App(app_ui, None)
## file: my-styles.css
.card-header {
    background: #2A2A2A;
    color: white
}
```

### Inline styles

Most UI components provide the opportunity to add an inline style (i.e., CSS that is applied directly to the element). This approach may be preferrable to an external CSS file if you only need to apply the style to one element, or if you want to apply style(s) programatically.

``` {shinylive-python}
#| standalone: true
#| components: [editor, viewer]
#| layout: vertical
#| viewerHeight: 150

from shiny import App, ui

app_ui = ui.page_fixed(
    ui.card(
        ui.card_header("Card header", style="background:#2A2A2A; color:white"),
        "Card body"
    )
)

app = App(app_ui, None)
```

### Utility classes

Since Shiny provides Bootstrap by default, you can use [Bootstrap utility classes](https://getbootstrap.com/docs/5.3/utilities/colors/) to customize your app. For example, you can `bg-primary` to change the background color, and `lead` to change the font weight. In addition to colors and fonts, utility classes are super useful for things like spacing, alignment, and borders.

Note this approach is similar to inline styles (i.e., per element styling), but has the advantage of abstracting the actual styling away from the element itself, which is especially useful when used in conjunction with [CSS variables](#css-variables).

``` {shinylive-python}
#| standalone: true
#| components: [editor, viewer]
#| layout: vertical
#| viewerHeight: 150

from shiny import App, ui

app_ui = ui.page_fixed(
    ui.card(
        ui.card_header("Card header", class_="bg-primary-subtle lead"),
        "Card body"
    )
)

app = App(app_ui, None)
```

### CSS Variables {#css-variables}

Bootstrap's [CSS variables](https://getbootstrap.com/docs/5.3/customize/css-variables/) provide another nice entry point to customizing your app, especially if you want to make sweeping changes to Bootstrap's default styles. For example, you can change the primary color by setting the `--bs-primary-rgb` variable.

``` {shinylive-python}
#| standalone: true
#| components: [editor, viewer]
#| layout: vertical
#| viewerHeight: 150

from shiny import App, ui

app_ui = ui.page_fixed(
    ui.tags.style(":root { --bs-primary-rgb: 113,46,246; }"),
    ui.card(
        ui.card_header("Card header", class_="bg-primary lead"),
        "Card body"
    )
)

app = App(app_ui, None)
```


## Custom fonts

If you want to use a custom font, you can use the `ui.tags.link()` function to import a font from a CDN. You can then use the font in your CSS.

<!---
### Including static files

If you have a static files like a CSS file, an image, or something else, you can use them available your app by placing them in a `www` directory (as a sibling to your `app.py` file). Then, to import those files, you can use `ui.include_css()`, `ui.include_js()`, or `ui.tags.img()` (for images).
--->


<!--
TODO: pick the best ideas from below
--->




# Inline styling

Container UI functions like `div`, `page_fluid`, `row`, and `column` can accept inline CSS directly.
To do this all you do is pass a dictionary with a `style` element to the ui function with the CSS code you want to apply to that element.

Inline CSS is handy because you don't need to switch back and forth between your CSS file and you application code, and it also allows you to easily apply CSS to one element rather than all of the elements of a particular class.
If you want to apply inline styles to a function like `output_text` which does not accept a dictionary, the best approach is to wrap it in `div` and pass the dictionary to the parent div.

::: callout-tip
You can use the `htmltools.css` function to conveniently create CSS.
This is particularly useful if you're creating the CSS programatically.

``` python
from htmltools import css

style=css(font_weight="bold", color="red)
# equivalent to style="font-weight: bold; color: red;"
```
:::


``` {shinylive-python}
#| standalone: true
#| components: [editor, viewer]
#| layout: vertical

from shiny import App, Inputs, Outputs, Session, render, ui

app_ui = ui.page_fluid(
  {"style": "background-color: rgba(0, 128, 255, 0.1)"},
    ui.input_slider("num", "Number:", min=10, max=100, value=30),
  ui.div(
    {"style": "font-weight: bold;"},
    ui.output_text("slider_val"),
  ),
)


def server(input: Inputs, output: Outputs, session: Session):
    @output
    @render.text
    def slider_val():
        return f"{input.num()}"


app = App(app_ui, server)
```

# Global styling

If you have styling which you would like to apply globally across your app you can do that by inserting it with `ui.tags.style`.
This function applies CSS across the application, and can be more convenient than an external file.

``` {shinylive-python}
#| standalone: true
#| components: [editor, viewer]
#| layout: vertical

from shiny import App, Inputs, Outputs, Session, render, ui

app_ui = ui.page_fluid(
    ui.tags.style(
        """
        body {
            font-family: Times
            }
        """
    ),
    ui.input_slider("num", "Number:", min=10, max=100, value=30),
    ui.output_text("slider_val"),
)


def server(input: Inputs, output: Outputs, session: Session):
    @output
    @render.text
    def slider_val():
        return f"{input.num()}"


app = App(app_ui, server)

```


# Using an external CSS file

If you find yourself copying CSS code between several components your best solution is to switch to an external CSS file.
The CSS file is imported into the app with the `ui.include_css()` function.
You can either modify existing classes like `row` or `column` or add additional classes with the same attribute dictionary you used for styles.
If you're not sure which class to change, open up your app in Chrome, right-click on the element you're interested in and select "Inspect".

::: callout-tip
If you have an existing CSS file which you use to customize an R Shiny app, you should be able to use it in a Python app without modification.
Note that Shiny for Python does not yet support [bslib](https://rstudio.github.io/bslib/) so transferring styles from a bslib styles R app may cause issues.
:::

``` {shinylive-python}
#| standalone: true
#| components: [editor, viewer]
#| layout: vertical

from pathlib import Path

from shiny import App, Inputs, Outputs, Session, render, ui

css_path = Path(__file__).parent / "www" / "my-styles.css"

app_ui = ui.page_fluid(
    {"class": "blue-body"},
    ui.include_css(css_path),
    ui.input_slider("num", "Number:", min=10, max=100, value=30),
    ui.div(
        {"class": "bold-output;"},
        ui.output_text("slider_val"),
    ),
)


def server(input: Inputs, output: Outputs, session: Session):
    @output
    @render.text
    def slider_val():
        return f"{input.num()}"


app = App(app_ui, server)
## file: www/my-styles.css
.blue-body {
  background-color: rgba(0, 128, 255, 0.5);
}

.bold-output {
  font-weight: bold;
}
```

# Sharing styles with other users

The [shinyswatch](https://github.com/posit-dev/py-shinyswatch) package provides a good template for sharing Shiny styles.
To share styles with a Python package you need two main things:

1)  Include the CSS and JavaScript assets in a subdirectory in your Python package.
    It is a good idea to [minify](https://www.minifier.org/) these assets to improve app performance.

2)  Have a function which points to those assets and returns an HTMLDependency
    You can also point the source to a CDN-hosted CSS file if you want the CSS to be loaded dynamically.

``` python
from htmltools import HTMLDependency

def acme_theme():
    subdir = os.path.join(os.path.dirname(__file__), "bsw5", name)

    # Contains both bootstrap and bootswatch css
    html_dep = HTMLDependency(
        name=f"acme_theme",
        version="0.01",
        source={"package": <package-name>, "subdir": subdir},
        stylesheet=[{"href": "acme-theme.css"}],
    )

    return html_dep
```

After the user installs your package, they will be able to call this function anywhere in their UI code to insert the theme.










## UI is HTML {#ui-is-html}

Underneath the hood, Shiny UI is based on HTML. In fact, if you print out a Shiny UI object, you'll see its HTML representation:

```python
from shiny import ui

ui.page_fluid(
    ui.h1("Hello, world!"),
    ui.output_plot("my_plot")
)
```

```html
<div class="container-fluid">
  <h1>Hello, world!</h1>
  <div id="my_plot" class="shiny-plot-output"></div>
</div>
```




The user interface (UI) of a Shiny application is HTML, but in most cases, you will use wrapper functions that make it easier to create the HTML. To get the most out of user interfaces, it's important to understand the relationship between Shiny's UI functions and the HTML that they generate.

UI components are available via the `shiny.ui` submodule. At the most basic level, you can create HTML tags by calling a correspondingly named function. For example, to create a `<div>` tag, you would call `ui.div()`.

```{shinylive-python}
#| components: [editor, cell]

from shiny import ui
ui.div("Hello!")
```

Tags can be nested:

```{shinylive-python}
#| components: [editor, cell]

ui.div("Hello", ui.span("World"), "!")
```

You can provide tag attributes (like `href`) with named arguments. Note that in Python, named arguments must go after unnamed arguments.

```{shinylive-python}
#| components: [editor, cell]

ui.a("Help", href="help.html")
```

Another way to do it is by passing in a dictionary of attributes. You can use the `{}` syntax or `dict()`:

```{shinylive-python}
#| components: [editor, cell]

# Both of these are equivalent:
ui.a({"href": "help.html"}, "Help")
ui.a(dict(href="help.html"), "Help")
```

In Python, there are some reserved keywords which can't be used as argument names, such as `class`. To get around this, you can either use a dictionary as above, or append an underscore to the argument. If there's a trailing `_`, it will be stripped off when creating the tag object.

```{shinylive-python}
#| components: [editor, cell]

# Two ways of doing the same thing
ui.a({"href": "help.html", "class": "help-link"}, "Help")
ui.a("Help", href="help.html", class_="help-link")
```

For convenience, common tags like `div`, `span`, and `a` are available directly from the `ui` submodule. All HTML tags are also available via `ui.tags`, so if you need to use a less common tag like `li`, you can use `ui.tags.li()`

Sometimes it it useful to return several tag objects together, but in a way where they are not nested within another tag. You can use a `TagList()` for this:

```{shinylive-python}
#| components: [editor, cell]

ui.TagList(
    ui.div("Hello"),
    ui.span("World"),
    "!"
)
```


## UI components

Most Shiny UI code doesn't require you to use functions like `div()` to write raw HTML. Instead, there are convenience functions that wrap up the HTML tags.

For example, `ui.input_checkbox()` generates the following HTML:

```{shinylive-python}
#| components: [editor, cell]

ui.input_checkbox("enable", "Enable?")
```

A complete UI for a Shiny app will put components in a `page_` function. Here is a simple page with a checkbox input and a text output.

```{shinylive-python}
#| components: [editor, cell]

from shiny import ui

ui.page_fluid(
    ui.input_checkbox("enable", "Enable?"),
    ui.output_text_verbatim("txt"),
)
```

Broadly speaking, there are three categories of UI components: layout components, inputs, and outputs. The `page_fluid()` is a layout component, and it contains one input and one output.

:::{.callout-tip}
## Shiny for Python compared to R

In Shiny for Python, the page-related functions start with `page_`, the input-related functions start with `input_`, and the output-related functions start with `output_`. This is different from Shiny for R, where the functions are named `fluidPage`, `checkboxInput`, and `textOutput`.
:::


This is what the application looks like. Note that there's no server logic, so it doesn't actually _do_ anything yet.

```{shinylive-python}
#| standalone: true
#| components: [editor, viewer]
#| layout: vertical

from shiny import App, ui

app_ui = ui.page_fluid(
    ui.input_checkbox("enable", "Enable?"),
    ui.h3("Is it enabled?"),
    ui.output_text_verbatim("txt", placeholder=True),
)

app = App(app_ui, None)
```
